<?php
namespace Apps\Controller;
use Common\Controller\AppBaseController;
/**
 * 首页
 */
//define("TOKEN", "xiaochen");
//define("APPID", "wx7325155f62456567");
//define("APPSECRET", "02e05630f28c9a54f11f17c788995ac5");

class WeChatController extends AppBaseController
{

    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stubindex
        if(I("schoolid")){
            $schoolid = I("schoolid");
            $result = M("wxmanage")->where("schoolid=$schoolid")->find();
            $this->schoolid = $schoolid;
            $this->appid = $result["wx_appid"];
            $this->appsecret = $result["wx_appsecret"];
            $_SESSION["APPID"] = $this->appid;
            $_SESSION["APPSECRET"] = $this->appsecret;

        }else{
            $this->appid = "wx7325155f62456567";
            $this->appsecret = "c379e9768f9faa8865a1db767fc81155";
            $_SESSION["APPID"] = $this->appid;
            $_SESSION["APPSECRET"] = $this->appsecret;
        }
    }
    //判断是介入还是用户  只有第一次介入的时候才会返回echostr
    function index()
    {
        $echoStr = $_GET["echostr"];
        if ($this->checkSignature()) {
            echo $echoStr;
            exit;
        }
    }

    //验证微信开发者模式接入是否成功
    private function checkSignature()
    {
        $signature = $_GET["signature"];
        $timestamp = $_GET["timestamp"];
        $nonce     = $_GET["nonce"];

        $token  = "xiaochen";
        $tmpArr = array(
            $token,
            $timestamp,
            $nonce
        );
        // use SORT_STRING rule
        sort($tmpArr, SORT_STRING);
        $tmpStr = implode($tmpArr);
        $tmpStr = sha1($tmpStr);

        if ($tmpStr == $signature) {
            echo "1111";
        } else {
            echo "2222";
        }
    }
    //获取 access_token
    function getAccess_token()
    {
        $appid = $this->appid;
        $appsecret = $this->appsecret;

        $result = M("wxmanage")->where("wx_appid = '$appid'")->find(); //令牌刷新时间

        $time = $result["token_expire_int"]; //令牌过期时间
		//第一次是access_token不存在 就重新获取一个
        if (time()>$time  || empty($time)) {
            //获取token
//            $url = "https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=" . APPID . "&secret=" . APPSECRET;
            $url = "https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=" . $appid . "&secret=" . $appsecret;
            //获取token
            $ch  = curl_init();
            curl_setopt($ch, CURLOPT_URL, $url);
            curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE);
            curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, FALSE);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
            $output = curl_exec($ch);
            curl_close($ch);
            $jsoninfo                   = json_decode($output, true);
            $access_token               = $jsoninfo["access_token"];
            //重新写进 数据库
            $data["token_expire_timeint"] = time();
            $data["authorizer_access_token"]       = $access_token;
            $data["token_expire_int"]       = time()+6500;
            $data["token_refresh_timeint"]       = time();
            $res   = M("wxmanage")->where("wx_appid = '$appid'")->save($data);
        } else {
            $arr = M("wxmanage")->where("wx_appid = '$appid'")->find();
            $access_token = $arr["authorizer_access_token"];
        }
        return $access_token;
    }

    //设置自定义菜单 前台传值过来 ajax 菜单创建的数据
    function createMenu()
    {
//        $data = '{"button":[
//           {
//              "type":"view",
//              "name":"微校园",
//              "url":"http://mp.zhixiaoyuan.net/index.php/weixin/Schoolweb/index"
//          },
//          {
//               "type":"view",
//               "name":"空间",
//               "url":"http://mp.zhixiaoyuan.net/index.php/weixin/Accredit/accept"
//          },
//          {
//               "name":"在线客服",
//               "sub_button":[
//                {
//                   "type":"click",
//                   "name":"hello word",
//                   "key":""
//                },
//                {
//                   "type":"click",
//                   "name":"在线绑定",
//                   "key":""
//                }]
//           }]
//}';
        $data = '{
     "button":[
     {
          "type":"view",
          "name":"微校园",
          "url":"http://mp.zhixiaoyuan.net/index.php/weixin/Schoolweb/index?schoolid=4"
      },
      {
           "type":"view",
           "name":"空间",
           "url":"http://mp.zhixiaoyuan.net/index.php/weixin/Accredit/accept?schoolid=4"
      },
      {
           "name":"在线客服",
           "sub_button":[
            {
               "type":"view",
               "name":"账号绑定",
               "url":"http://mp.zhixiaoyuan.net/index.php/weixin/index/accept?schoolid=4"
            }]
       }]
}';

        $access_token = $this->getAccess_token();
        $url          = "https://api.weixin.qq.com/cgi-bin/menu/create?access_token=" . $access_token;
        $content      = $data;
        $res          = $this->https_request($url, $content);
        dump($res);
        return $res;

    }
    //获取自定义菜单
    public function getMenu()
    {
        $this->createMenu();//调用菜单
        $access_token = $this->getAccess_token();
        $getMenuurl   = "https://api.weixin.qq.com/cgi-bin/menu/get?access_token=" . $access_token;
        $ch           = curl_init();
        curl_setopt($ch, CURLOPT_URL, $getMenuurl);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE);
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, FALSE);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        $output = curl_exec($ch);
        curl_close($ch);
        $res = json_decode($output, true);
        header("Content-type: text/html; charset=utf-8");
        print_r($res);
    }

    //删除自定义菜单
    public function delMenu()
    {
        $access_token = $this->getAccess_token();
        $delMenuurl   = "https://api.weixin.qq.com/cgi-bin/menu/delete?access_token=" . $access_token;
        $result = $this->https_request($delMenuurl);
    }



    //构建一个发送请求的curl方法  微信的东西都是用这个 直接百度
    function https_request($url, $data = null)
    {
        $curl = curl_init();
        curl_setopt($curl, CURLOPT_URL, $url);
        curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, FALSE);
        curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, FALSE);
        if (!empty($data)){
            curl_setopt($curl, CURLOPT_POST, 1);
            curl_setopt($curl, CURLOPT_POSTFIELDS, $data);
        }
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
        $output = curl_exec($curl);
        curl_close($curl);
        return $output;
    }



    //构建模板信息发送方法
    function sendTemplate($tpl)
    {
        $json_template = json_encode($tpl);
        $access_token  = $this->getAccess_token();
        $url           = "https://api.weixin.qq.com/cgi-bin/message/template/send?access_token==" . $access_token;
        $tmpArr        = json_decode($json_template, true);
    }
    //这是到学校的通知
    //定义一个方法 直接获取学生的各种信息
    function getInfo($resJson)
    {
        //把接收过来的json转化为数组
        $receive  = json_decode($resJson, true);
        $stu_id   = $receive["id"];
        //通过学生表找到家长的openid
        //获取学生姓名
        $stu_name = M("student_info")->where("$stu_id = id")->find("name");
        //获取学生表的userid
        $userid   = M("student_info")->where("$stu_id = id")->find("userid");
        //通过学生表的userid获取家长的微信openid
        $openid   = M("wxtusers")->where("$userid = id")->find("weixin");
        //获取刷卡地点怎么获取还没搞清楚 暂时定义为$place
        $place    = $receive["place"];
        $info     = array(
            $receive,
            $stu_id,
            $stu_name,
            $userid,
            $openid,
            $place
        );
        return $info;
    }
    function sendReach_school($resJson)
    {
        $tpl = array(
            //接收者
            "touser" => $res[$openid],
            //模板id
            "template_id" => "1d555qPObIhA8tpj6YZzYNA-TEEWvWjR7sEJSvog3aQ",
            //点击跳转的url
            "url" => "http://xct.zjxxt.net.cn/wxt/kaoqin.html",
            //标题颜色
            "topcolor" => "#436EEE",
            //模板的数据了  里面的东西都要和微信的模板一一对应
            "data" => array(
                "first" => array(
                    "value" => "尊敬的" . $res[$stu_name] . "家长，" . $res[$stu_name] . "同学有一条考勤消息：：",
                    "color" => "#436EEE"
                ),
                "keyword1" => array(
                    "value" => $res[$stu_name],
                    "color" => "#436EEE"
                ),
                //                "keyword2" => array("value" => "小一班","color" => "#436EEE"),
                "keyword2" => array(
                    "value" => date('Y-m-d H:i:s', "1487894880"),
                    "color" => "#436EEE"
                ),
                "keyword3" => array(
                    "value" => $res[$place],
                    "color" => "#436EEE"
                ),
                "remark" => array(
                    "value" => $res[$stu_name] . "已平安到校，请您放心",
                    "color" => "#436EEE"
                )
            )
        );
        $res = $this->sendTemplate($tpl);
        if ($res["errcode"] == 0) {
            echo "发送成功";
        } else {
            echo json_encode($res);
        }
    }
    //离校通知
    function Leaveschool()
    {
        $res = $this->getInfo();
        $tpl = array(
            //接收者
            "touser" => "oImI6wwYnHtsz5V4yMkkYuPwIwJw",
            "template_id" => "xpkhD2C-tSMGvdndrc7EWJnbNI8s548QzH87sDgNo5g",
            "url" => "http://xct.zjxxt.net.cn/wxt/kaoqin.html",
            "topcolor" => "#436EEE",
            "data" => array(
                "first" => array(
                    "value" => "尊敬的家长：下面是您的小孩打卡离校的情况：",
                    "color" => "#436EEE"
                ),
                "keyword1" => array(
                    "value" => $res[$stu_name],
                    "color" => "#436EEE"
                ),
                "keyword2" => array(
                    "value" => "小一班",
                    "color" => "#436EEE"
                ),
                "keyword3" => array(
                    "value" => $res[$place],
                    "color" => "#436EEE"
                ),
                "keyword4" => array(
                    "value" => date('Y-m-d H:i:s'),
                    "color" => "#436EEE"
                ),
                "remark" => array(
                    "value" => "请注意小孩的回家时间，谢谢您的查收！",
                    "color" => "#436EEE"
                )
            )
        );
    $this->sendTemplate($tpl);
    }//模板发送结束
    //获取用户列表 全部用户的列表
    function getUserlist(){
        $access_token = $this->getAccess_token();
        $url = "https://api.weixin.qq.com/cgi-bin/user/get?access_token=".$access_token."&next_openid=500";
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE);
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, FALSE);
        $output = curl_exec($ch);
        curl_close($ch);
        return $output;
    }


} //classend