<?php
  namespace Weixin\Controller;
use Common\Controller\WeixinbaseController;
class CookbookController extends WeixinbaseController {
	//http://localhost/weixiaotong2016/index.php/weixin/Cookbook/index

    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $userid = I("userid");
        //获取微信的openid
        $openid  = I("openid");
        //获取学生的id
        $studentid = I("studentid");
        $schoolid  = I("schoolid");//学校ID
        $classid = I("classid");
        $appid = I("appid");//获取公众号的appid
        $appsecret = I("appsecret");//获取公众号的appsecret
        //判断是否有空
        if(empty($userid) || empty($openid) || empty($studentid)||empty($appid) ||empty($schoolid) ||empty($appsecret)){
            unset($userid);
            unset($openid);
            unset($studentid);
            unset($appid);
            unset($appsecret);
            unset($schoolid);
        }else{
            $_SESSION["APPID"] = $appid;
            $_SESSION["APPSECRET"] = $appsecret;
            $_SESSION["user"]["weixin"] = $openid;
            //        $res = M("wxtuser")->where(array("id"=>$userid,"weixin"=>$openid))->find();
            $res = M("xctuserwechat")->where(array("userid"=>$userid,"weixin"=>$openid))->find();
            if ($res){
                $_SESSION["userid"] = $userid;
                $_SESSION["studentid"] = $studentid;
                $_SESSION["classid"] = $classid;
                //查出学校的名字
                $sch_info = M("school")->where(array('schoolid' => $schoolid))->find();
                if ($sch_info){
                    $_SESSION["school_name"] = $sch_info["school_name"];
                    $_SESSION["schoolid"] = $sch_info["schoolid"];
                }
            }
        }


    }

    //本周食谱
    public function index(){
        $date = I("date");
        $stu_sch_name = $_SESSION["school_name"];
        $this->assign("schoolname",$stu_sch_name);
        $userid = $_SESSION['userid'];
        if($_SESSION['schoolid']){
            $this->assign('schoolid',$_SESSION['schoolid']);
        }
        //查找年级
        if($_SESSION['classid']){
            $classid = $_SESSION['classid'];
            $result = M("school_class")->where("id = '$classid'")->find();
            $this->assign('grade',$result['grade']);
        }
        $this->assign("date",$date);
        $this->display();
    }

    /*$schoolid 学校id  $grade 年级ID $date 当前日期 2018-1-29
 * 获取食谱列表
 */

    public function getCookbookContent()
    {
        $schoolid = I("schoolid");//学校ID
        $grade = I("grade");//年级ID
        $date = I("date");//日期
        if(empty($schoolid) || empty($grade) || empty($grade)){
            $ret = array("state"=>"error","date"=>"参数不足,获取失败");
            echo json_encode($ret);
            exit;
        }
        $cook_time=$this->getdays($date);//获得星期一和星期日的世界
       // $result = M('cookbook')->where(array("schoolid"=>$schoolid,"grade"=>$grade,"mondaydate"=>$cook_time[0],"sundaydate"=>$cook_time[1]))->find();
        $mondaydate = $cook_time[0];
        $sundaydate = $cook_time[1];
        $where = array(
            "schoolid"=>$schoolid,
            "grade"=>$grade,
            "mondaydate"=>$mondaydate,
            "sundaydate"=>$sundaydate,
            "timingtype"=>array('neq',1)
        );

        // $result = M('cookbook')->where(array("schoolid"=>$schoolid,"grade"=>$grade,"mondaydate"=>$cook_time[0],"sundaydate"=>$cook_time[1]))->find();
        $result = M('cookbook')->where($where)->find();
        if(empty($result)){
            $ret = array("state"=>"error","data"=>"本周没有食谱");
            echo json_encode($ret);
            exit;
        }
        $cookbookid= $result["id"];//食谱ID
        $cooklist = M('cookbook_detail')->where(array("cookbookid"=>$cookbookid))->order('week asc')->select();
        if(empty($cooklist)){
            $ret = array("state"=>"error","data"=>"未获取到数据");
            echo json_encode($ret);
            exit;
        }else{
            foreach ($cooklist as &$value){
                $value["title"] = $result["title"];
            }
            $ret = array("state"=>"success","data"=>$cooklist);
            echo json_encode($ret);
            exit;
        }
    }

    public function getCookbooks()
    {
        $cookbookid= I("cookbookid");//食谱ID
        $result = M('cookbook')->where(array("id"=>$cookbookid))->find();
        $cooklist = M('cookbook_detail')->where(array("cookbookid"=>$cookbookid))->order('week asc')->select();
        if(empty($cooklist)){
            $ret = array("state"=>"error","data"=>"未获取到数据");
            echo json_encode($ret);
            exit;
        }else{
            foreach ($cooklist as &$value){
                $value["title"] = $result["title"];
            }
            $ret = array("state"=>"success","data"=>$cooklist);
            echo json_encode($ret);
            exit;
        }
    }


    public function getCookbook()
    {
        $schoolid = I("schoolid");//学校ID
        $grade = I("grade");//年级ID
        $where = array(
            "schoolid"=>$schoolid,
            "grade"=>$grade,
            "timingtype"=>array('neq',1)
        );

        $result = M('cookbook')->where($where)->order("id asc")->field("id,title")->select();
        //$result = M('cookbook')->where(array("schoolid"=>$schoolid,"grade"=>$grade))->order("id asc")->field("id,title")->select();
        $newarray=array();
        foreach ($result as $value){
            $id = $value["id"];
            $title = $value["title"];
            $newarray[]=array("id"=>$id,"value"=>$title);

        }
        //$cc = json_encode($newarray);
//        dump($cc);
        if(empty($result)){
            $ret = array("state"=>"error","data"=>"未获取到数据");
            echo json_encode($ret);
            exit;
        }else{
            $ret = array("state"=>"success","data"=>$newarray);
            echo json_encode($ret);
            //echo $cc;
            exit;
        }
    }
    function getdays($day){
        $lastday=date('Y-m-d',strtotime("$day Sunday"));
        $firstday=date('Y-m-d',strtotime("$lastday -6 days"));
        return array($firstday,$lastday);
    }
}
?>