<?php
namespace Weixin\Controller;
use Common\Controller\WeixinbaseController;
class HomeworkController extends WeixinbaseController {
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $type = I("type");
        if($type){
            $id = I("id");
            $stu_id = I("stu_id");
            $school_id = I("school_id");
            $this->check_menu($id,$stu_id,$school_id);
            return;
        }
        $userid = I("userid");
        //获取微信的openid
        $openid  = I("openid");
        //获取学生的id
        $studentid = I("studentid");
        $schoolid = I("schoolid");//学校ID
        $appid = I("appid");//获取公众号的appid
        $appsecret = I("appsecret");//获取公众号的appsecret
        //判断是否有空
        if(empty($userid) || empty($openid) || empty($studentid)||empty($appid) ||empty($schoolid) ||empty($appsecret)){
            unset($userid);
            unset($openid);
            unset($studentid);
            unset($appid);
            unset($appsecret);
            unset($schoolid);
        }else{
            $_SESSION["APPID"] = $appid;
            $_SESSION["APPSECRET"] = $appsecret;
            $_SESSION["user"]["weixin"] = $openid;
            //$res = M("wxtuser")->where(array("id"=>$userid,"weixin"=>$openid))->find();
            $res = M("xctuserwechat")->where(array("userid"=>$userid,"weixin"=>$openid))->find();
            if ($res){
                $_SESSION["userid"] = $userid;
                $_SESSION["studentid"] = $studentid;
                //顺带查出来学校id 学校名字 学生班级
                $sch_info = M("school")->where(array('schoolid' => $schoolid))->find();
                if ($sch_info){
                    $_SESSION["school_name"] = $sch_info["school_name"];
                    $_SESSION["schoolid"] = $sch_info["schoolid"];
                }
            }
//            }
        }

    }
	//	localhost/weixiaotong2016/index.php/weixin/Homework/index
	//作业
	public function index(){
        $stu_sch_name = $_SESSION["school_name"];
        $this->assign("schoolname",$stu_sch_name);
	    $receive = $_SESSION['studentid'];
	    $this->assign("receive",$receive);
        $schoolid = $_SESSION['schoolid'];
        $this->assign("schoolid",$schoolid);
		$this->display();
	}

    //作业详情
    public function details(){
        header("Content-type: text/html; charset=utf-8");
        $receiverid = I("receiverid"); //学生ID
        $homework_id = I("homework_id");//作业ID
        $schoolid = $_SESSION["schoolid"];
        //调用APPS详情接口
        $array =$this->gethomeworkmessage_detasils($receiverid,$homework_id,$schoolid);
        //$array=R("Apps/Student/gethomeworkmessage_detasils",array("receiverid"=>$receiverid,"homework_id"=>$homework_id));
        $result = json_decode($array,true);

        $stu_sch_name = $_SESSION["school_name"];//学校名称
        $this->assign("schoolname",$stu_sch_name);
        $title = $result["data"][0]["homework_info"][0]["title"];//标题
        $content = $result["data"][0]["homework_info"][0]["content"];//内容
        $subject = $result["data"][0]["homework_info"][0]["subject"];//科目
        $name = $result["data"][0]["homework_info"][0]["name"];//名字
        $photo = $result["data"][0]["homework_info"][0]["photo"];//头像
        $create_time = date('Y-m-d H:i:s',$result["data"][0]["homework_info"][0]["create_time"]);//发布时间
        $read_time = $result["data"][0]["read_time"];

        $readarray = $result["data"][0]["receive_list"];

        $h=0;
        foreach($readarray  as $k=>$v){
            if($v["read_time"]>0){
                $h++;
            }
        }
        $zongshu = count($readarray); //总数
        $yushu = $h; //已读
        $Wei=$zongshu-$h;//未读


        $subContent = $result["data"][0]['picture'];//图片
        if(count($subContent)==0){
            $sub=1;
        }else{
            $subContent=$subContent;
            $sub=0;
        }

//        if(!empty($receiverid) && !empty($homework_id) && !empty($read_time)){
//            $homework = M("homework_receive");
//            $homework->where(array("homework_id"=>$homework_id,"receiverid"=>$receiverid))->save(array("read_time"=>time()));//变为已读
//        }



        $this->assign("zongshu",$zongshu);
        $this->assign("yushu",$yushu);
        $this->assign("Wei",$Wei) ;
        $this->assign("sub",$sub);
        $this->assign("photo",$photo);
        $this->assign("receiverid",$receiverid);
        $this->assign("homework_id",$homework_id);
        $this->assign("title",$title);
        $this->assign("content",$content);
        $this->assign("subject",$subject);
        $this->assign("name",$name);
        $this->assign("create_time",$create_time);
        $this->assign("read_time",$read_time);
        $this->assign("subContent",$subContent);
        $this->display();
    }

    //学生-获取作业信息详情
    public function gethomeworkmessage_detasils($receiverid,$homework_id,$schoolid){
//        $receiverid = Intval(I('receiverid')); //学生ID
//        $homework_id = Intval(I('homework_id')); //作业ID
        $receive=M('homework_receive')
            ->alias("a")
            ->join("wxt_homework b ON a.homework_id=b.id")
            ->order("b.create_time DESC")
            ->distinct(true)
            ->field("a.id,homework_id,receiverid,read_time")
            ->where("receiverid=$receiverid and homework_id = $homework_id")
            // ->order("id DESC")
            ->select();
        foreach ($receive as &$homework) {
//            $send_message=M('homework_receive')
//                ->alias("r")
//                ->join("wxt_homework u ON r.homework_id=u.id")
            $send_message=M('homework as u')
                ->field("u.id,u.title,u.userid,u.subject,u.content,u.create_time")
                ->distinct(true)
                ->order("u.create_time ASC")
                ->where(array("u.id"=>$homework['homework_id']))
                ->select();
            foreach ($send_message as &$name) {
                $username=M('wxtuser')->field("name,photo")->where(array("id"=>$name['userid']))->find();
                $teacherinfo=M('teacher_info')->field("name")->where(array("teacherid"=>$name['userid'],"schoolid"=>$schoolid))->find();
                $name['name']=$teacherinfo['name'];
                $name['photo']=$username['photo'];
            }
            $homework["homework_info"]=$send_message;
            //获取接收人列表
            $receive_list=M('homework_receive')
                ->alias("h")
                ->join("wxt_wxtuser w ON h.receiverid=w.id")
                ->where(array("h.homework_id"=>$homework['homework_id']))
                ->field("w.name,w.photo,w.phone,h.receiverid,h.read_time")
                ->select();
            $homework["receive_list"]=$receive_list;
            //获取图片
            $pic=M('homework_pic')->field("picture_url,width,height")->where(array("homework_id"=>$homework['homework_id']))->select();
            $homework['picture']=$pic;
            for ($j=0; $j < count($pic); $j++) {
                $homework['picture'][$j]["picturewidth"]=$pic[$j]["width"];
                $homework['picture'][$j]["pictureheight"]=$pic[$j]["height"];
            }
            unset($homework);
        }
        if($receive){
            $ret = $this->format_ret(1,$receive);
        }else{
            $ret = $this->format_ret(0,'未获取到数据');
        }
        return json_encode($ret);

    }
}
?>