<?php
namespace Weixin\Controller;
use Common\Controller\WeixinbaseController;
class TchanswerController extends WeixinbaseController {

    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
//        $type = I("type");
//        if($type){
//            $id = I("id");
//            $stu_id = I("stu_id");
//            $school_id = I("school_id");
//            $this->check_menu($id,$stu_id,$school_id);
//            return;
//        }

        $userid = I("userid");//获得用户ID
        $openid  = I("openid");//获取微信的openid
        $schoolid  = I("schoolid");//获得学校ID
        $appid = I("appid");//获取公众号的appid
        $appsecret = I("appsecret");//获取公众号的appsecret
//        判断有没有空
        if (empty($userid) || empty($openid)||empty($appid) ||empty($schoolid) ||empty($appsecret) ){
            unset($userid);
            unset($openid);
            unset($appid);
            unset($appsecret);
            unset($schoolid);
        }else {
            $_SESSION["APPID"] = $appid;
            $_SESSION["APPSECRET"] = $appsecret;
            $_SESSION["user"]["weixin"] = $openid;
            //开始写session
            $_SESSION["userid"] = $userid;
            //查询学校id 学校名字
            $sch_info = M("school")->where(array('schoolid' => $schoolid))->find();
            if ($sch_info) {
                $_SESSION["schoold_name"] = $sch_info["school_name"];
                $_SESSION["schoolid"] = $sch_info["schoolid"];
            }

        }
    }

	//教师端代接控制器
	//localhost/weixiaotong2016/index.php/weixin/Tchanswer/index
	public function index(){
        $stu_sch_name = $_SESSION["school_name"];
        $this->assign("schoolname",$stu_sch_name);
	    $this->assign('userid',$_SESSION['userid']);
        $this->assign('schoolid',$_SESSION['schoolid']);
	   $this->display("dai-daichuli");
	}
	
	public function daiJie(){
        $stu_sch_name = $_SESSION["school_name"];
        $this->assign("schoolname",$stu_sch_name);

        $this->assign('userid',$_SESSION['userid']);
        $this->assign('schoolid',$_SESSION['schoolid']);
		$this->display("dai-yiwancheng");
	}
	//提交的控制器
	public function Submit(){
        $stu_sch_name = $_SESSION["school_name"];
        $this->assign("schoolname",$stu_sch_name);
//        $jssdk = new JSSDK("wx7325155f62456567","c379e9768f9faa8865a1db767fc81155");
//        $signPackage = $jssdk->getSignPackage();
        $signPackage = $this->getSignPackage();
        $this->assign('signPackage',$signPackage);
        $this->assign('userid',$_SESSION['userid']);
        $this->assign('schoolid',$_SESSION['schoolid']);
        $this->display("Answer_Parent");
	}

	public function parent(){
	    $studentid = I('studentid');
        $parentlist = M("relation_stu_user")->where(array('studentid' => $studentid))->field("userid")->find();
        $user = M("wxtuser")->where(array('id' => $parentlist['userid']))->field("phone")->find();
        if(count($user)){
            echo json_encode(array('data'=>$user['phone'],'message'=>'数据查找成功'));
        }else{
            echo json_encode(array('data'=>0,'message'=>'数据查找失败'));
        }
    }

}


