<?php
	namespace Weixin\Controller;
use Common\Controller\WeixinbaseController;
class TchagencyController extends WeixinbaseController {
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stubindex
        $userid = I("userid");
        //获取微信的openid
        $openid  = I("openid");
        $schoolid  = I("schoolid");//学校ID
        $appid = I("appid");//获取公众号的appid
        $appsecret = I("appsecret");//获取公众号的appsecret

        //判断是否有空
        if (empty($userid) || empty($openid) ||empty($appid) ||empty($schoolid) ||empty($appsecret)){
            unset($userid);
            unset($openid);
            unset($appid);
            unset($appsecret);
            unset($schoolid);
        }else{
            $_SESSION["APPID"] = $appid;
            $_SESSION["APPSECRET"] = $appsecret;
            $_SESSION["user"]["weixin"] = $openid;
            $res = M("xctuserwechat")->where(array("userid"=>$userid,"weixin"=>$openid))->find();
                if ($res) {
                    $_SESSION["userid"] = $userid;
                    //顺带查出来学校id 学校名字 学生班级
                    $sch_info = M("school")->where(array('schoolid' => $schoolid))->find();
                    if ($sch_info) {
                        $_SESSION["school_name"] = $sch_info["school_name"];
                        $_SESSION["schoolid"] = $sch_info["schoolid"];
                    }
                }

        }
    }
	//以获取的事项
	public function index(){
        $stu_sch_name = $_SESSION["school_name"];
        $this->assign("schoolname",$stu_sch_name);
        $userid = $_SESSION['userid'];
        $this->assign("userid",$userid);
        if(empty($_SESSION['schoolid'])){
            $school = M("teacher_class")->where("teacherid = '$userid'")->find();
            $this->assign("schoolid",$school['schoolid']);
        }else{
            $this->assign("schoolid",$_SESSION['schoolid']);
        }
		$this->display("daibanshi");
	}

	//发布事宜
    public function Answer() {
//        $jssdk = new JSSDK("wx7325155f62456567","c379e9768f9faa8865a1db767fc81155");
//        $signPackage = $jssdk->GetSignPackage();
        $signPackage = $this->getSignPackage();
        $this->assign('signPackage',$signPackage);
        $stu_sch_name = $_SESSION["school_name"];
        $this->assign("schoolname",$stu_sch_name);
        $teacherid = $_SESSION['userid'];
        $this->assign("teacherid",$teacherid);
       // $schoolid = M("teacher_class")->where(array("teacherid" => $teacherid))->find();
        $this->assign('schoolid', $_SESSION['schoolid']);
        $this->assign('userid', $_SESSION['userid']);
        $this->display("MessageBoard");
    }

    //已发布事项
    public function  tasksList() {
        $stu_sch_name = $_SESSION["school_name"];
        $this->assign("schoolname",$stu_sch_name);$this->assign("schoolname",$stu_sch_name);
        $userid = $_SESSION['userid'];
        if(empty($_SESSION['schoolid'])){
            $school = M("teacher_class")->where("teacherid = '$userid'")->find();
            $this->assign("schoolid",$school['schoolid']);
        }else{
            $this->assign("schoolid",$_SESSION['schoolid']);
        }
        $this->assign("userid", $userid);
        $this->display("tasklist");
    }
    //已发布事项详情
    public function details() {
        $stu_sch_name = $_SESSION["school_name"];
        $schoolid = $_SESSION['schoolid'];
        $userid = $_SESSION['userid'];
        $scheduleid = I('scheduleid');

        $this->assign("schoolname",$stu_sch_name);//学校名字
        $this->assign("scheduleid",$scheduleid);//事宜ID
        $this->assign("schoolid",$schoolid);//学校ID
        $this->assign("userid",$userid);
        $this->display("taskdetails");
    }

    //已获取事项详情
    public function detail() {
        $stu_sch_name = $_SESSION["school_name"];
        $schoolid = $_SESSION['schoolid'];
        $userid = $_SESSION['userid'];//用户ID
        $scheduleid = I('scheduleid');//事项ID
        $rid= I('rid');//关系表ID
        //echo $rid;
        $readtime= I('readtime');//关系表ID
       // echo $readtime;
        if(($readtime=='null')){
            $recive_model=M('schedule_reception');
            $where["id"]=$rid;
            $updatadata["read_time"]=time();
            $recive_model->where($where)->save($updatadata);//变为已接收
        }
        //echo  $rid;

        $this->assign("schoolname",$stu_sch_name);//学校名字
        $this->assign("id", $rid);//学校名字
        $this->assign("scheduleid",$scheduleid);//事宜ID
        $this->assign("schoolid",$schoolid);//学校ID
        $this->assign("userid",$userid);
        $this->display("daibandetails");
    }

    //处理事宜
    public function DoTask() {
	    $scheduleid=I('scheduleid');//事宜ID
	    $rid = I('rid');//处理ID
        $this->assign('scheduleid',$scheduleid);
        $this->assign('rid',$rid);

        $name = I('name');//发起人姓名
        $content = I('content');//发起人内容
        $this->assign('name',$name);
        $this->assign('content',$content);

        $stu_sch_name = $_SESSION["school_name"];
        $this->assign("schoolname",$stu_sch_name);
        $teacherid = $_SESSION['userid'];
        $this->assign("teacherid",$teacherid);
//        $schoolid = M("teacher_class")->where(array("teacherid" => $teacherid))->find();
        $this->assign('schoolid', $_SESSION['schoolid']);
        $this->assign('userid', $_SESSION['userid']);
        $this->display("dotask");
    }
}



?>