<?php
namespace Weixin\Controller;
use Common\Controller\WeixinbaseController;
class ActivityController extends WeixinbaseController {
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $type = I("type");
        if($type){
            $id = I("id");
            $stu_id = I("stu_id");
            $school_id = I("school_id");
            $this->check_menu($id,$stu_id,$school_id);
            return;
        }
        $userid = I("userid");
        //获取微信的openid
        $openid  = I("openid");
        //获取学生的id
        $studentid = I("studentid");
        $schoolid = I("schoolid");//学校ID
        $appid = I("appid");//获取公众号的appid
        $appsecret = I("appsecret");//获取公众号的appsecret
        //判断是否有空
        if(empty($userid) || empty($openid) || empty($studentid)||empty($appid) ||empty($schoolid) ||empty($appsecret)){
            unset($userid);
            unset($openid);
            unset($studentid);
            unset($appid);
            unset($appsecret);
            unset($schoolid);
        }else{
            $_SESSION["APPID"] = $appid;
            $_SESSION["APPSECRET"] = $appsecret;
            $_SESSION["user"]["weixin"] = $openid;
            //$res = M("wxtuser")->where(array("id"=>$userid,"weixin"=>$openid))->find();
            $res = M("xctuserwechat")->where(array("userid"=>$userid,"weixin"=>$openid))->find();
            if ($res){
                $_SESSION["userid"] = $userid;
                $_SESSION["studentid"] = $studentid;
                //顺带查出来学校id 学校名字 学生班级
                $sch_info = M("school")->where(array('schoolid' => $schoolid))->find();
                if ($sch_info){
                    $_SESSION["school_name"] = $sch_info["school_name"];
                    $_SESSION["schoolid"] = $sch_info["schoolid"];
                }
            }
//            }
        }

    }
//	localhost/weixiaotong2016/index.php/weixin/Activity/index
	//班级活动控制器
	   public function index(){
        //dump($_SESSION);
           $stu_sch_name = $_SESSION["school_name"];
           $this->assign("schoolname",$stu_sch_name);
	       $this->assign('userid',$_SESSION['studentid']);
	       $this->assign('schoolid',$_SESSION['schoolid']);
	    	$this->display();
	   }

    //活动详情
    public function details(){
        header("Content-type: text/html; charset=utf-8");
        $receiverid = I("receiverid"); //学生ID
        $activity_id = I("activity_id"); //活动ID
        $schoolid = $_SESSION["schoolid"];
        //调用APPS详情接口
        //$array=R("Apps/Student/getactivitylist_details",array("receiverid"=>$receiverid,"activity_id"=>$activity_id));
        $array=$this->getactivitylist_details($receiverid,$activity_id,$schoolid);

        $result = json_decode($array,true);
        //dump($result);

        $stu_sch_name = $_SESSION["school_name"];
        $this->assign("schoolname",$stu_sch_name);
        $begintime = date('Y-m-d H:i:s',$result["data"][0]["activity_list"][0]["begintime"]);//活动开始的时间
        $endtime = date('Y-m-d H:i:s',$result["data"][0]["activity_list"][0]["endtime"]);//活动结束的时间
        $starttime = date('Y-m-d H:i:s',$result["data"][0]["activity_list"][0]["starttime"]);//活动报名开始的时间
        $stime = $result["data"][0]["activity_list"][0]["starttime"];
        $finishtime = date('Y-m-d H:i:s',$result["data"][0]["activity_list"][0]["finishtime"]);//活动报名结束时间
        $ftime = $result["data"][0]["activity_list"][0]["finishtime"];//活动报名结束时间
        $tiet = $result["data"][0]["activity_list"][0]["title"];//标题
        $content = $result["data"][0]["activity_list"][0]["content"];//内容
        $contactphone = $result["data"][0]["activity_list"][0]["contactphone"];//号码
        $shuzhu4 = $result["data"][0]["activity_list"][0]["user_info"][0]["name"];//发布人名字
        $zhaopian4 = $result["data"][0]["activity_list"][0]["user_info"][0]["photo"];//发布人头像
        $shijian = date('Y-m-d',$result["data"][0]["activity_list"][0]["create_time"]);//活动发布时间
        $nuMber = count($result["data"][0]["apply_count"]);
        $userid = $receiverid;

        $arr = $result["data"][0]["apply_count"];
        //print_r($arr);
        if($nuMber){
            foreach($arr as $v){
                if($v["userid"]==$receiverid){
                    $isapply =1;
                    break;
                }else{
                    $isapply =-1;
                }
            }

        }else{
            $isapply =-1;
        }



        if(!empty($activity_id)){//活动ID
            $User = M("activity_receive"); //修改阅读状态
            $data['read_time'] = time();
            $where = array("activity_id"=>$activity_id,"receiverid"=>$receiverid);
            $User->where($where)->save($data); //

        }

        $subContent = $result["data"][0]['pic'];//图片
        if(count($subContent)==0){
            $sub=1;
        }else{
            $subContent=$subContent;
            $sub=0;
        }
        $this->assign("nuMber",$nuMber);
        $this->assign("sub",$sub);

        $this->assign("ftime",$ftime);
        $this->assign("stime",$stime);
        $this->assign("title",$tiet);
        $this->assign("content",$content);
        $this->assign("zhaopian4",$zhaopian4);
        $this->assign("shuzhu4",$shuzhu4);
        $this->assign("shijian",$shijian);
        $this->assign("begintime",$begintime);
        $this->assign("endtime",$endtime);
        $this->assign("starttime",$starttime);
        $this->assign("finishtime",$finishtime);
        $this->assign("isapply",$isapply);
        $this->assign("contactphone",$contactphone);
        $this->assign("subContent",$subContent);
//        $this->assign("receiverid",$receiverid);
        $this->assign("receiverid",$activity_id);
        $this->assign("userid",$userid);
        $this->display();
    }

    //家长端-获取班级活动信息详情
    public function getactivitylist_details($receiverid,$activity_id,$schoolid){
        //传入接收人id
        $teacher_where["teacher.schoolid"]=$schoolid;
        //获取接收表中对应接收id的信息
        $receive=M('activity_receive')
            ->field("id,activity_id,receiverid,read_time")
            ->where("receiverid=$receiverid and activity_id=$activity_id ")
            ->order("id DESC")
            ->select();
        //通过获取到的activity_id在主表中查询出对应的活动信息
        foreach ($receive as &$activity) {
            $active_id=$activity['activity_id'];
            $active=M('activity')
                ->field("id,userid,classid,title,content,contactman,contactphone,begintime,endtime,starttime,finishtime,isapply,create_time")
                ->where("id=$active_id")
                ->select();
            foreach ($active as &$activeinfo) {
                $user_id=$activeinfo['userid'];
                $teacher_where["a.id"] =  $user_id;
               // $active_info=M('teacher_info as teacher')->field("teacher.name")->where($teacher_where)->select();
                $active_info=M('wxtuser as a')->join("wxt_teacher_info as teacher on teacher.teacherid=a.id")->field("teacher.name,a.photo")->where($teacher_where)->select();
                $activeinfo['user_info']=$active_info;
            }
            $activity['activity_list']=$active;
            //获取图片
            $pic=M('activity_pic')->field("picture_url,width,height")->where(array("activity_id"=>$activity['activity_id']))->select();
            $activity['pic']=$pic;
            for ($j=0; $j < count($pic); $j++) {
                $activity['pic'][$j]["picturewidth"]=$pic[$j]["width"];
                $activity['pic'][$j]["pictureheight"]=$pic[$j]["height"];
            }
            //报名列表
            $apply_model=M('entryactivity');
            $apply_count = $apply_model->field("userid")->distinct(true)->where("activityid=$active_id")->select();
            $activity["apply_count"]=$apply_count;
            unset($activity);
        }
        if($receive){
            $ret = $this->format_ret(1,$receive);
        }else{
            $ret = $this->format_ret(0,'未获取到数据');
        }
        return json_encode($ret);
    }
}
?>