<?php
namespace Weixin\Controller;
use Common\Controller\WeixinbaseController;
class ReplaceController extends WeixinbaseController {
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $userid = I("userid");
        //获取微信的openid
        $openid  = I("openid");
        //获取学生的id
        $studentid = I("studentid");
        $schoolid = I("schoolid");//学校ID
        $appid = I("appid");//获取公众号的appid
        $appsecret = I("appsecret");//获取公众号的appsecret
        //判断是否有空
        if(empty($userid) || empty($openid) || empty($studentid)||empty($appid) ||empty($schoolid) ||empty($appsecret)){
            unset($userid);
            unset($openid);
            unset($studentid);
            unset($appid);
            unset($appsecret);
            unset($schoolid);
        }else{
            $_SESSION["APPID"] = $appid;
            $_SESSION["APPSECRET"] = $appsecret;
            $_SESSION["user"]["weixin"] = $openid;
            //$res = M("wxtuser")->where(array("id"=>$userid,"weixin"=>$openid))->find();
            $res = M("xctuserwechat")->where(array("userid"=>$userid,"weixin"=>$openid))->find();
            if ($res){
                $_SESSION["userid"] = $userid;
                $_SESSION["studentid"] = $studentid;
                //顺带查出来学校id 学校名字 学生班级
                $sch_info = M("school")->where(array('schoolid' => $schoolid))->find();
                if ($sch_info){
                    $_SESSION["school_name"] = $sch_info["school_name"];
                    $_SESSION["schoolid"] = $sch_info["schoolid"];
                }
            }
//            }
        }

    }
	//代接控制器
	//http://localhost/weixiaotong2016/index.php/weixin/Replace/Handle
	//当天待处理的渲染页面
	public function Handle(){
        $stu_sch_name = $_SESSION["school_name"];
        $this->assign("schoolname",$stu_sch_name);
	    $this->assign('userid',$_SESSION['userid']);
	    $this->assign("studentid",$_SESSION['studentid']);
        $this->assign('schoolid',$_SESSION['schoolid']);
//	    var_dump($_SESSION);die();
		$this->display();
	}
	//已完成的渲染
	public function  Finish(){
        $stu_sch_name = $_SESSION["school_name"];
        $this->assign("schoolname",$stu_sch_name);
        $this->assign("studentid",$_SESSION['studentid']);
        $this->assign('schoolid',$_SESSION['schoolid']);
		$this->display();
	}
	//未处理的代接信息
	public function Overdue(){
        $stu_sch_name = $_SESSION["school_name"];
        $this->assign("schoolname",$stu_sch_name);
        $this->assign("studentid",$_SESSION['studentid']);
        $this->assign('schoolid',$_SESSION['schoolid']);
		$this->display();
	}
}
?>