<?php
namespace Weixin\Controller;
use Common\Controller\WeixinbaseController;
class TchExamController extends WeixinbaseController {
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $type = I("type");
        if($type){
            $id = I("id");
            $stu_id = I("stu_id");
            $school_id = I("school_id");
            $this->check_menu($id,$stu_id,$school_id);
            return;
        }
        $userid = I("userid");//获得用户ID
        $openid  = I("openid");//获取微信的openid
        $schoolid  = I("schoolid");//获得学校ID
        $appid = I("appid");//获取公众号的appid
        $appsecret = I("appsecret");//获取公众号的appsecret
//        判断有没有空
        if (empty($userid) || empty($openid)||empty($appid) ||empty($schoolid) ||empty($appsecret) ){
            unset($userid);
            unset($openid);
            unset($appid);
            unset($appsecret);
            unset($schoolid);
        }else {
            $_SESSION["APPID"] = $appid;
            $_SESSION["APPSECRET"] = $appsecret;
            $_SESSION["user"]["weixin"] = $openid;
            //开始写session
            $_SESSION["userid"] = $userid;
            //查询学校id 学校名字
            $sch_info = M("school")->where(array('schoolid' => $schoolid))->find();
            if ($sch_info) {
                $_SESSION["schoold_name"] = $sch_info["school_name"];
                $_SESSION["schoolid"] = $sch_info["schoolid"];
            }

        }

    }

    //老师成绩首页
    public function index(){
        $stu_sch_name = $_SESSION["school_name"];
        $this->assign("schoolname",$stu_sch_name);
        $userid = $_SESSION["userid"];
        $schoolid=$_SESSION['schoolid'];
        //老师所在班级
        $class = M("teacher_class as class")
            ->distinct(true)
            ->join("wxt_school_class as schoolclass on class.schoolid = schoolclass.schoolid and schoolclass.id = class.classid")
            ->where("class.schoolid = '$schoolid' and teacherid = '$userid'")
            ->field("class.classid,schoolclass.classname")
            ->select();
        // dump($class);
        $this->assign("class",$class);
        $this->display();
    }

    //学生考试成绩首页
    public function exam_index(){
        $classid = I("classid");//班级ID
        $stu_sch_name = $_SESSION["school_name"];
        $this->assign("schoolname",$stu_sch_name);
        //dump($_SESSION);
        $where["b.schoolid"] = $_SESSION["schoolid"];
        $where["a.classid"] = $classid;
        $exam = M("exam_class as a ")->
        join("wxt_exam as b on a.examid=b.id")->
        join("wxt_semester as c on c.id=b.semester")->where($where)
            ->field("b.*,c.semester,a.classid,a.examid")->select();
        //dump($exam);
        $this->assign("exam",$exam);
        $this->display("exam_index");
    }

    //学生列表
    public function stuList(){
        $examid = I("examid");//考试ID
        $classid = I("classid");//班级ID
        $result = M("class_relationship as a")->
        join("wxt_wxtuser as b on a.userid=b.id")->
        join("wxt_student_info as student on student.userid=b.id")->
        where("a.classid = $classid")->field("a.userid,student.stu_name as name,b.photo")->select();
        //dump($result);
        $this->assign("result",$result);
        $this->assign("classid",$classid);
        $this->assign("examid",$examid);
        $this->display("stuList");
    }

    //学生考试成绩详情
    public  function  details(){
        //这个考试 这个学生的各个科目的考试成绩
        $examid = I("examid");//考试ID
        $classid = I("classid");//班级ID
        $studentid = I("studentid");

        //考试评论
        $comment = M("exam_comment")->where("examid=$examid and classid=$classid and studentid=$studentid")->find();
        $this->assign("comment",$comment);

        $score = M("exam_score as a")->join("wxt_default_subject as b on a.subjectid=b.id")
            ->where("a.examid=$examid and a.classid=$classid and a.studentid=$studentid")
            ->field("a.*,b.subject")->select();
        // dump($score);
        $totalscore=0;
        $key=0;
        foreach ($score as $k=>$value){
            $totalscore+=$value["score"];
            $key++;
        }
        $kscore = $totalscore/$key;
        $this->assign("totalscore",$totalscore);
        $this->assign("kscore",$kscore);
        $this->assign("score",$score);
        $this->display();
    }




}
?>