<?php
namespace Weixin\Controller;
use Common\Controller\WeixinbaseController;
class TchSignInController extends WeixinbaseController {
	//http://localhost/weixiaotong2016/index.php/weixin/TchSignIn/index
	//教师考勤考勤的渲染页面
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $type = I("type");
        if($type){
            $id = I("id");
            $stu_id = I("stu_id");
            $school_id = I("school_id");
            $this->check_menu($id,$stu_id,$school_id);
            return;
        }
        $userid = I("userid");//获得用户ID
        $openid  = I("openid");//获取微信的openid
        $schoolid  = I("schoolid");//获得学校ID
        $appid = I("appid");//获取公众号的appid
        $appsecret = I("appsecret");//获取公众号的appsecret
//        判断有没有空
        if (empty($userid) || empty($openid)||empty($appid) ||empty($schoolid) ||empty($appsecret) ){
            unset($userid);
            unset($openid);
            unset($appid);
            unset($appsecret);
            unset($schoolid);
        }else {
            $_SESSION["APPID"] = $appid;
            $_SESSION["APPSECRET"] = $appsecret;
            $_SESSION["user"]["weixin"] = $openid;
            //开始写session
            $_SESSION["userid"] = $userid;
            //查询学校id 学校名字
            $sch_info = M("school")->where(array('schoolid' => $schoolid))->find();
            if ($sch_info) {
                $_SESSION["schoold_name"] = $sch_info["school_name"];
                $_SESSION["schoolid"] = $sch_info["schoolid"];
            }

        }
    }
	public function index(){
        $stu_sch_name = $_SESSION["school_name"];
        $this->assign("schoolname",$stu_sch_name);
		$thismonth = date('m');
            $thisyear = date('Y');
             $startDay = $thisyear . '-' . $thismonth . '-1';
               $endDay = $thisyear . '-' . $thismonth . '-' . date('t', strtotime($startDay));
            $b_time  = strtotime($startDay);//当前月的月初时间戳
          $e_time  = strtotime($endDay);//当前月的月末时间戳
        $this->assign("teacherid",$_SESSION['userid']);
		$this->assign("b_time",$b_time);
		$this->assign("e_time",$e_time);
		$this->assign("schoolid",$_SESSION['schoolid']);
		$this->display();
	}

	//学生统计页面
    public function classlist(){
        $stu_sch_name = $_SESSION["school_name"];
        $this->assign("schoolname",$stu_sch_name);
        $userid = $_SESSION['userid'];
        $schoolid = $_SESSION['schoolid'];
        $this->assign("userid",$userid);
        $this->assign("schoolid",$schoolid);
        $this->display();
    }

    //老师统计页面
    public function teacherlist(){
        $stu_sch_name = $_SESSION["school_name"];
        $this->assign("schoolname",$stu_sch_name);
        $userid = $_SESSION['userid'];
        $schoolid = $_SESSION['schoolid'];
        $this->assign("userid",$userid);
        $this->assign("schoolid",$schoolid);
        $this->display();

    }


}
?>