<?php
namespace Weixin\Controller;
use Common\Controller\WeixinbaseController;
header("Content-type:text/html;charset=utf-8");
class GrowthdiaryController extends WeixinbaseController {
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $userid = I("userid");
        //获取微信的openid
        $openid  = I("openid");
        //获取学生的id
        $studentid = I("studentid");
        $schoolid = I("schoolid");//学校ID
        $appid = I("appid");//获取公众号的appid
        $appsecret = I("appsecret");//获取公众号的appsecret
        //判断是否有空
        if(empty($userid) || empty($openid) || empty($studentid)||empty($appid) ||empty($schoolid) ||empty($appsecret)){
            unset($userid);
            unset($openid);
            unset($studentid);
            unset($appid);
            unset($appsecret);
            unset($schoolid);
        }else{
            $_SESSION["APPID"] = $appid;
            $_SESSION["APPSECRET"] = $appsecret;
            $_SESSION["user"]["weixin"] = $openid;
            //$res = M("wxtuser")->where(array("id"=>$userid,"weixin"=>$openid))->find();
            $res = M("xctuserwechat")->where(array("userid"=>$userid,"weixin"=>$openid))->find();
            if ($res){
                $_SESSION["userid"] = $userid;
                $_SESSION["studentid"] = $studentid;
                //顺带查出来学校id 学校名字 学生班级
                $sch_info = M("school")->where(array('schoolid' => $schoolid))->find();
                if ($sch_info){
                    $_SESSION["school_name"] = $sch_info["school_name"];
                    $_SESSION["schoolid"] = $sch_info["schoolid"];
                }
            }
//            }
        }

    }
    public function index(){
        $stu_sch_name = $_SESSION["school_name"];
        $this->assign("schoolname",$stu_sch_name);
        $userid = $_SESSION["userid"];
        $studentid = $_SESSION['studentid'];
        if(empty($_SESSION['classid'])){
            $info = M("class_relationship")->where(array("userid"=>$studentid))->find();
            $_SESSION['classid'] = $info['classid'];
            $_SESSION['schoolid'] = $info['schoolid'];
        }
        $this->assign("userid",$userid);
        //获取学生姓名
        $stu_info = M("wxtuser")->where(array("id"=>$studentid))->find();
        $this->assign("name",$stu_info['name']);
        //获取用户姓名
//        $user_info = M("wxtuser")->where(array("id"=>$userid))->find();
//        $this->assign("username",$user_info['name']);
        $user_info = M("relation_stu_user")->where(array("userid"=>$userid,"studentid"=>$studentid))->field("name")->find();
        $this->assign("username",$user_info['name']);
        $this->assign("classid",$_SESSION['classid']);
        $this->assign("schoolid",$_SESSION['schoolid']);
        $this->assign("studentid",$studentid);
        $this->display();
    }
    public function addDiray(){
        $stu_sch_name = $_SESSION["school_name"];
        $this->assign("schoolname",$stu_sch_name);
//        $jssdk = new JSSDK("wx7325155f62456567","c379e9768f9faa8865a1db767fc81155");
//        $signPackage = $jssdk->getSignPackage();
        $signPackage = $this->getSignPackage();
        $this->assign('signPackage',$signPackage);
        //获取babyid
        $studentid = $_SESSION['studentid'];
        $userid = $_SESSION["userid"];
        $user_info = M("student_info")->where(array("userid"=>$_SESSION['studentid']))->field("stu_name")->find();
        $this->assign('send_name',$user_info["stu_name"]);

        $this->assign("userid",$userid);
        $this->assign("classid",$_SESSION['classid']);
        $this->assign("schoolid",$_SESSION['schoolid']);
        $this->assign("studentid",$studentid);
        $this->display();
    }
    function GetFriendsGrow(){
        $stu_sch_name = $_SESSION["school_name"];
        $this->assign("schoolname",$stu_sch_name);
        $studentid = $_SESSION["studentid"];
        $this->assign("studentid",$studentid);
        $this->display();
    }
   }


