<?php
/**
 * Created by PhpStorm.
 * User: 消息渲染
 * Date: 2017/2/14
 * Time: 15:21
 */
//  localhost/weixiaotong2016/index.php/weixin/Message/index
//消息
namespace Weixin\Controller;
use Common\Controller\WeixinbaseController;
class MessageController extends WeixinbaseController {

    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $type = I("type");
        if($type){
            $id = I("id");
            $stu_id = I("stu_id");
            $school_id = I("school_id");
            $this->check_menu($id,$stu_id,$school_id);
            return;
        }

        $userid = I("userid");
        //获取微信的openid
        $openid  = I("openid");
        //获取学生的id
        $studentid = I("studentid");
        $schoolid = I("schoolid");//学校ID
        $appid = I("appid");//获取公众号的appid
        $appsecret = I("appsecret");//获取公众号的appsecret
        //判断是否有空
        if(empty($userid) || empty($openid) || empty($studentid)||empty($appid) ||empty($schoolid) ||empty($appsecret)){
            unset($userid);
            unset($openid);
            unset($studentid);
            unset($appid);
            unset($appsecret);
            unset($schoolid);
        }else{
            $_SESSION["APPID"] = $appid;
            $_SESSION["APPSECRET"] = $appsecret;
            $_SESSION["user"]["weixin"] = $openid;
            //$res = M("wxtuser")->where(array("id"=>$userid,"weixin"=>$openid))->find();
            $res = M("xctuserwechat")->where(array("userid"=>$userid,"weixin"=>$openid))->find();
            if ($res){
                $_SESSION["userid"] = $userid;
                $_SESSION["studentid"] = $studentid;
                //顺带查出来学校id 学校名字 学生班级
                $sch_info = M("school")->where(array('schoolid' => $schoolid))->find();
                if ($sch_info){
                    $_SESSION["school_name"] = $sch_info["school_name"];
                    $_SESSION["schoolid"] = $sch_info["schoolid"];
                }
            }
//            }
        }

    }

	//消息的渲染页面
    public function index(){
        $stu_sch_name = $_SESSION["school_name"];
        $this->assign("schoolname",$stu_sch_name);//学校名字
        $this->assign('userid',$_SESSION['studentid']);//学生ID
        $this->assign('schoolid',$_SESSION['schoolid']);//学校ID
        $this->display();
    }


    public function details(){
        $receiver_user_id = I("receiver_user_id");
        $message_id = I("message_id");
        $schoolid = $_SESSION["schoolid"];
        //调用APPS详情接口
        //$array=R("Apps/Message/user_reception_message_details",array("receiver_user_id"=>$receiver_user_id,"message_id"=>$message_id));
        $array=$this->user_reception_message_details($receiver_user_id,$message_id,$schoolid);
        $result = json_decode($array,true);
//        echo "<pre>";
//        print_r($result);
        $stu_sch_name = $_SESSION["school_name"];
        $this->assign("schoolname",$stu_sch_name);
        $name = $result["data"][0]["send_message"][0]["send_user_name"];//发布人名字
        $content = $result["data"][0]["send_message"][0]["message_content"];//内容
        $message_time = date('Y-m-d H:i:s',$result["data"][0]["send_message"][0]["message_time"]);//发布时间
        $message = $result["data"][0]["read_time"];//是否读取
        if($message==""){
            $message=0;
        }

        //已读 未读
        $readarray = $result["data"][0]["receiver"];
        $h=0;
        foreach($readarray  as $k=>$v){
            if($v["read_time"]>0){
                $h++;
            }
        }
        $zong = count($readarray); //总数
        $yidu = $h; //已读
        $Weidu=$zong-$h;//未读
        $subContent = $result["data"][0]['pic'];//图片
        if(count($subContent)==0){
            $sub=1;
        }else{
            $subContent=$subContent;
            $sub=0;
        }
//        echo   $sub;
//        print_r($subContent);
        $photo = $result["data"][0]["send_message"][0]["photo"];//头像

//        $zong=I("zong");
//        $yidu=I("yidu");
//        $Weidu=$zong-$yidu;
        $this->assign("Weidu",$Weidu);
        $this->assign("yidu",$yidu);
        $this->assign("zong",$zong);
        $this->assign("photo",$photo);
        $this->assign("sub",$sub);
        $this->assign("name",$name);
        $this->assign("content",$content);
        $this->assign("message_time",$message_time);
        $this->assign("message_id",$message_id);
        $this->assign("message",$message);
        $this->assign("receiver_user_id",$receiver_user_id);
        $this->assign("subContent",$subContent);
        $this->display();
    }


    //获取用户已接收的信息详情
    //$receiver_user_id 接收人ID $message_id 信息ID $schoolid 学校ID
    public function user_reception_message_details($receiver_user_id,$message_id,$schoolid){
        if($receiver_user_id){
            $message_where["receiver_user_id"] = $receiver_user_id;
        }else{
            $ret = $this->format_ret(0,'缺少参数');
            echo json_encode($ret);
            exit;
        }
        if($message_id){
            $message_where["message_id"] = $message_id;
        }
        if($schoolid){
            $message_where["schoolid"] = $schoolid;
            $user_where["u.schoolid"] = $schoolid;
            $user_where["teacher.schoolid"] = $schoolid;
        }
        $receive=M('user_message_reception')
            ->alias("a")
            ->field("a.id,a.message_id,a.receiver_user_id,a.receiver_user_name,a.message_type,a.read_time")
            // ->where("receiver_user_id=$receiver_user_id and message_id=$message_id")
            ->where($message_where)
            ->select();
        foreach ($receive as &$send) {
            $refid=$send['message_id'];
            $user_where["u.id"] = $refid;
            $send_message=M('user_message')
                ->alias("u")
                ->join("wxt_wxtuser w ON w.id=u.send_user_id")
                ->join("wxt_teacher_info teacher ON teacher.teacherid=u.send_user_id")
                ->field("u.id,u.schoolid,u.send_user_id,teacher.name as send_user_name,u.message_content,u.message_time,w.photo,u.type")
                //->where("u.id=$refid")
                ->where($user_where) //已发送
                //->where($user_where)
                ->order("message_time DESC")
                ->select();
            $send["send_message"]=$send_message;
            unset($send);
        }
        foreach ($receive as &$res_info) {
            $receiverid=$res_info['message_id'];
            $mes=M('user_message_reception')
                ->alias("u")
                ->join("wxt_wxtuser e ON u.receiver_user_id=e.id")
                ->field("message_id,receiver_user_id,receiver_user_name,read_time,photo,phone")
                ->where("u.message_id=$receiverid")
                ->select();
            $res_info['receiver']=$mes;
            //获取图片
            $pic=M('user_message_pic')->field("picture_url,width,height")->where("message_id=$receiverid")->select();
            $res_info['pic']=$pic;
            for ($j=0; $j < count($pic); $j++) {
                $res_info['pic'][$j]["picturewidth"]=$pic[$j]["width"];
                $res_info['pic'][$j]["pictureheight"]=$pic[$j]["height"];
            }
            unset($res_info);
        }
        if($receive){
            $ret = $this->format_ret(1,$receive);
        }else{
            $ret = $this->format_ret(0,'未获取到数据');
        }
        return json_encode($ret);
    }


}