<?php
namespace Weixin\Controller;
use Common\Controller\WeixinbaseController;
class MobilephoneController extends WeixinbaseController {
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $type = I("type");
        if($type){
            $id = I("id");
            $stu_id = I("stu_id");
            $school_id = I("school_id");
            $this->check_menu($id,$stu_id,$school_id);
            return;
        }

        $userid = I("userid");
        //获取微信的openid
        $openid  = I("openid");
        //获取学生的id
        $studentid = I("studentid");
        $schoolid = I("schoolid");//学校ID
        $appid = I("appid");//获取公众号的appid
        $appsecret = I("appsecret");//获取公众号的appsecret
        //判断是否有空
        if(empty($userid) || empty($openid) || empty($studentid)||empty($appid) ||empty($schoolid) ||empty($appsecret)){
            unset($userid);
            unset($openid);
            unset($studentid);
            unset($appid);
            unset($appsecret);
            unset($schoolid);
        }else{
            $_SESSION["APPID"] = $appid;
            $_SESSION["APPSECRET"] = $appsecret;
            $_SESSION["user"]["weixin"] = $openid;
            //$res = M("wxtuser")->where(array("id"=>$userid,"weixin"=>$openid))->find();
            $res = M("xctuserwechat")->where(array("userid"=>$userid,"weixin"=>$openid))->find();
            if ($res){
                $_SESSION["userid"] = $userid;
                $_SESSION["studentid"] = $studentid;
                //顺带查出来学校id 学校名字 学生班级
                $sch_info = M("school")->where(array('schoolid' => $schoolid))->find();
                if ($sch_info){
                    $_SESSION["school_name"] = $sch_info["school_name"];
                    $_SESSION["schoolid"] = $sch_info["schoolid"];
                }
            }
//            }
        }

    }
	//通讯录渲染页面
	//老师	localhost/weixiaotong2016/index.php/weixin/Mobilephone/index
	public function index(){
        $stu_sch_name = $_SESSION["school_name"];
        $this->assign("schoolname",$stu_sch_name);
	    $this->assign('studentid',$_SESSION['studentid']);
	    $this->assign('schoolid',$_SESSION['schoolid']);
		$this->display("tongxun-laoshi");
	}
	//家长
	public function Parent(){
        $stu_sch_name = $_SESSION["school_name"];
        $this->assign("schoolname",$stu_sch_name);
        $this->assign('studentid',$_SESSION['studentid']);
        $this->display("tongxun-jiazhang");
	}

    /** 图片等比例压缩
     * @param string $imgSrc 原图路径
     * @param int $maxwidth  设置图片的最大宽度
     * @param int $maxheight 设置图片的最大高度
     * @param string $filetype 图片类型
     */
    function resizeImage($imgSrc = "./uploads/microblog/20170906165232.jpg",$maxwidth = 250,$maxheight = 250,$filetype = "jpg"){
        //初始化图象
        if ($filetype == "jpg") {
            $im = imagecreatefromjpeg($imgSrc);
        }
        if ($filetype == "gif") {
            $im = imagecreatefromgif($imgSrc);
        }
        if ($filetype == "png") {
            $im = imagecreatefrompng($imgSrc);
        }

        //目标图象地址
        $name = end(explode("/",$imgSrc));
        $route = "./uploads/microbloghub/".$name;//压缩图片的位置

        $pic_width = imagesx($im);
        $pic_height = imagesy($im);
        if(($maxwidth && $pic_width > $maxwidth) || ($maxheight && $pic_height > $maxheight)){
            if($maxwidth && $pic_width>$maxwidth){
                $widthratio = $maxwidth/$pic_width;
                $resizewidth_tag = true;
            }
            if($maxheight && $pic_height>$maxheight) {
                $heightratio = $maxheight/$pic_height;
                $resizeheight_tag = true;
            }
            if($resizewidth_tag && $resizeheight_tag){
                if($widthratio<$heightratio)
                    $ratio = $widthratio;
                else
                    $ratio = $heightratio;
            }
            if($resizewidth_tag && !$resizeheight_tag)
                $ratio = $widthratio;
            if($resizeheight_tag && !$resizewidth_tag)
                $ratio = $heightratio;
            $newwidth = $pic_width * $ratio;
            $newheight = $pic_height * $ratio;
            if(function_exists("imagecopyresampled")){
                $newim = imagecreatetruecolor($newwidth,$newheight);
                imagecopyresampled($newim,$im,0,0,0,0,$newwidth,$newheight,$pic_width,$pic_height);//图像边缘比较平滑.质量较好(但速度比 ImageCopyResized() 慢
            }
            else{
                $newim = imagecreate($newwidth,$newheight);
                imagecopyresized($newim,$im,0,0,0,0,$newwidth,$newheight,$pic_width,$pic_height);//在所有GD版本中有效,缩放图像的算法比较粗糙
            }
            imagejpeg($newim,$route);
            imagedestroy($newim);
        }
        else{
            imagejpeg($im,$route);
            imagedestroy($im);
        }
    }


}
?>