<?php
namespace Weixin\Controller;
use Common\Controller\WeixinbaseController;
class TchattendanceController extends WeixinbaseController {
	//教师端学生考勤考勤
	//localhost/weixiaotong2016/index.php/weixin/Tchattendance/index
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $type = I("type");
        if($type){
            $id = I("id");
            $stu_id = I("stu_id");
            $school_id = I("school_id");
            $this->check_menu($id,$stu_id,$school_id);
            return;
        }
//        $this->check_session();//查看session 是否过期
        $userid = I("userid");//获得用户ID
        $openid  = I("openid");//获取微信的openid
        $schoolid  = I("schoolid");//获得学校ID
        $appid = I("appid");//获取公众号的appid
        $appsecret = I("appsecret");//获取公众号的appsecret
//        判断有没有空
        if (empty($userid) || empty($openid)||empty($appid) ||empty($schoolid) ||empty($appsecret) ){
            unset($userid);
            unset($openid);
            unset($appid);
            unset($appsecret);
            unset($schoolid);
        }else {
            $_SESSION["APPID"] = $appid;
            $_SESSION["APPSECRET"] = $appsecret;
            $_SESSION["user"]["weixin"] = $openid;
            //开始写session
            $_SESSION["userid"] = $userid;
            //查询学校id 学校名字
            $sch_info = M("school")->where(array('schoolid' => $schoolid))->find();
            if ($sch_info) {
                $_SESSION["schoold_name"] = $sch_info["school_name"];
                $_SESSION["schoolid"] = $sch_info["schoolid"];
            }

        }
    }

	public function index(){
        $stu_sch_name = $_SESSION["school_name"];
        $this->assign("schoolname",$stu_sch_name);
	    $userid = $_SESSION['userid'];
        if(I("schoolid") && I("classid")){
            $this->assign("classid",I("classid"));
            $this->assign('schoolid',I("schoolid"));
            $_SESSION["classid"] = I("classid");
        }else{

                $this->assign("classid",$_SESSION["classid"]);
                $this->assign('schoolid',$_SESSION["schoolid"]);

        }
        //dump($_SESSION);
		$this->display("class_check");
	}
	//教师端学生签退
	public function SignOut(){
        $stu_sch_name = $_SESSION["school_name"];
        $this->assign("schoolname",$stu_sch_name);
        $userid = $_SESSION['userid'];


                $this->assign("classid",$_SESSION["classid"]);
                $this->assign('schoolid',$_SESSION["schoolid"]);


		$this->display("class_nout");
	}
	
}
	
?>