<?php
namespace Weixin\Controller;
use Common\Controller\WeixinbaseController;
class TchHomeworkController extends WeixinbaseController {
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $type = I("type");
        if($type){
            $id = I("id");
            $stu_id = I("stu_id");
            $school_id = I("school_id");
            $this->check_menu($id,$stu_id,$school_id);
            return;
        }

        $userid = I("userid");//获得用户ID
        $openid  = I("openid");//获取微信的openid
        $schoolid  = I("schoolid");//获得学校ID
        $appid = I("appid");//获取公众号的appid
        $appsecret = I("appsecret");//获取公众号的appsecret
//        判断有没有空
        if (empty($userid) || empty($openid)||empty($appid) ||empty($schoolid) ||empty($appsecret) ){
            unset($userid);
            unset($openid);
            unset($appid);
            unset($appsecret);
            unset($schoolid);
        }else {
            $_SESSION["APPID"] = $appid;
            $_SESSION["APPSECRET"] = $appsecret;
            $_SESSION["user"]["weixin"] = $openid;
            //开始写session
            $_SESSION["userid"] = $userid;
            //查询学校id 学校名字
            $sch_info = M("school")->where(array('schoolid' => $schoolid))->find();
            if ($sch_info) {
                $_SESSION["schoold_name"] = $sch_info["school_name"];
                $_SESSION["schoolid"] = $sch_info["schoolid"];
            }

        }

    }
	//教师端作业
	public function index(){
        $stu_sch_name = $_SESSION["school_name"];
        $this->assign("schoolname",$stu_sch_name);
	    $userid = $_SESSION['userid'];
	    $this->assign('userid',$userid);
        $schoolid = $_SESSION['schoolid'];
        $this->assign('schoolid',$schoolid);
		$this->display("zuoye");
	}
    //教师作业添加
	public function add(){
        $stu_sch_name = $_SESSION["school_name"];//学校名称
        $this->assign("schoolname",$stu_sch_name);
        $signPackage = $this->getSignPackage();
        $this->assign('signPackage',$signPackage);
        $userid = $_SESSION['userid']; //老师ID
        $this->assign('userid',$userid);
        $schoolid = $_SESSION["schoolid"]; //学校ID
        $this->assign('schoolid',$schoolid);
		$this->display("Answer_Parent");
	}

    //作业详情
    public function details(){

        header("Content-type: text/html; charset=utf-8");
        $userid = I("userid"); //老师ID
        $homework_id = I("homework_id");//作业ID
        $schoolid =$_SESSION["schoolid"];
        //调用APPS详情接口
        //$array=R("Apps/Teacher/gethomeworklist_detasils",array("userid"=>$userid,"homework_id"=>$homework_id));
        $array= $this->gethomeworklist_detasils($userid,$homework_id,$schoolid);
        $result = json_decode($array,true);

        $stu_sch_name = $_SESSION["school_name"];//学校名称
        $this->assign("schoolname",$stu_sch_name);
        $title = $result["data"][0]["title"];//标题
        $content = $result["data"][0]["content"];//内容
        $subject = $result["data"][0]["subject"];//科目
        $name = $result["data"][0]["teacher_info"]["name"];//名字
        $photo = $result["data"][0]["teacher_info"]["photo"];//头像
        $create_time = date('Y-m-d H:i:s',$result["data"][0]["create_time"]);//发布时间
        $readarray = $result["data"][0]["receiverlist"];
        $h=0;
        foreach($readarray  as $k=>$v){
            if($v["read_time"]>0){
                $h++;
            }
        }
        $zongshu = count($readarray); //总数
        $yushu = $h; //已读
        $Wei=$zongshu-$h;//未读

        $subContent = $result["data"][0]['pic'];//图片
        if(count($subContent)==0){
            $sub=1;
        }else{
            $subContent=$subContent;
            $sub=0;
        }

        $this->assign("homework_id",$homework_id);
        $this->assign("zongshu",$zongshu);
        $this->assign("yushu",$yushu);
        $this->assign("Wei",$Wei) ;
        $this->assign("sub",$sub);
        $this->assign("photo",$photo);

        $this->assign("title",$title);
        $this->assign("content",$content);
        $this->assign("subject",$subject);
        $this->assign("name",$name);
        $this->assign("create_time",$create_time);
        $this->assign("subContent",$subContent);
        $this->display();
    }

    //老师获取作业信息列表 详情
    public function gethomeworklist_detasils($userid,$homework_id,$schoolid){
//        $userid = intval(I('userid'));//老师ID
//        $homework_id = intval(I('homework_id')); //作业ID
//        $schoolid = $_SESSION["schoolid"];

        if($userid){
            $homework_where["userid"] = $userid;
            $homework_where["id"] =  $homework_id;
            $teacher_where["wxt_wxtuser.id"] = $userid;

        }
        if($schoolid){
            $homework_where["schoolid"] = $schoolid;
            $teacher_where["teacher.schoolid"] = $schoolid;
        }
        if($userid){
            $homework_model = M('homework');
            $lists=$homework_model
                ->field('id,userid,title,subject,content,photo,create_time')
//                ->where("userid=$userid and id=$homework_id")
                ->where($homework_where)
                ->order('id desc')
                ->select();
            foreach ($lists as &$homework ) {
                $refid =$homework["id"];
                //接收人列表
                $receive_model=M('homework_receive');
                $receiver=$receive_model->field("id,homework_id,receiverid,read_time")->where("homework_id=$refid")->select();
                foreach ($receiver as &$receiverinfo) {
                    $user_id=$receiverinfo["receiverid"];
                    $receiver_info=M('wxtuser')
                        ->field("name,photo,phone")
                        ->where("id=$user_id")
                        ->select();
                    $receiverinfo['receiver_info']=$receiver_info;
                    unset($receiverinfo);
                }
                $homework['receiverlist']=$receiver;
                //老师信息
                $user_model=M('wxtuser');
                $userinfo=$user_model->join("wxt_teacher_info teacher on teacher.teacherid=wxt_wxtuser.id")->field("teacher.name,photo")->where($teacher_where)->find();
                $homework['teacher_info']=$userinfo;
                //获取图片
                $pic=M('homework_pic')->field("picture_url,width,height")->where(array("homework_id"=>$homework['id']))->select();
                $homework['pic']=$pic;
                for ($j=0; $j < count($pic); $j++) {
                    # code...
//                    $imagesize = getimagesize("/alidata/www/weixiaotong2016/uploads/microbloghub/".$pic[$j]["picture_url"]);
//                    $homework['pic'][$j]["picturewidth"]=$imagesize["0"];
//                    $homework['pic'][$j]["pictureheight"]=$imagesize["1"];
                    $homework['pic'][$j]["picturewidth"]=$pic[$j]["width"];
                    $homework['pic'][$j]["pictureheight"]=$pic[$j]["height"];
                }
                unset($homework);
            }
            $ret = $this->format_ret(1,$lists);

        }
        else{
            $ret = $this->format_ret(0,"lost params");
        }
        return json_encode($ret);
    }
    //查看已读未读
    public function read(){
        $stu_sch_name = $_SESSION["school_name"];
        $this->assign("schoolname",$stu_sch_name);
        $homework_id=$_GET["homework_id"];
        $model = M();
        $sql = "SELECT s.stu_name as name,w.phone,w.photo,w.id FROM wxt_homework_receive r  JOIN wxt_wxtuser w on r.receiverid=w.id JOIN wxt_student_info s on s.userid=w.id WHERE ( r.homework_id='$homework_id' and r.read_time>0)";
        $arr = "SELECT s.stu_name as name,w.phone,w.photo,w.id FROM wxt_homework_receive r  JOIN wxt_wxtuser w on r.receiverid=w.id JOIN wxt_student_info s on s.userid=w.id WHERE ( r.homework_id='$homework_id' and r.read_time is null)";
        $receive_list = $model->query($sql);
        $rlist = $model->query($arr);
        foreach($receive_list as &$value)
        {
            $studentid = $value["id"];//学生ID
            $result = M("relation_stu_user as a")->join("wxt_wxtuser as b on a.userid=b.id")->field("b.phone")->where("a.studentid=$studentid")->find();
            $value["phone"] = $result["phone"];
        }

        foreach($rlist as &$value)
        {
            $studentid = $value["id"];//学生ID
            $result = M("relation_stu_user as a")->join("wxt_wxtuser as b on a.userid=b.id")->field("b.phone")->where("a.studentid=$studentid")->find();
            $value["phone"] = $result["phone"];
        }
        $this->assign("receive_list",$receive_list);//已读人数
        $this->assign("rlist",$rlist);//未读人数
        $this->display( );
    }
}


