<?php
namespace Weixin\Controller;
use Common\Controller\WeixinbaseController;
class TchInformationController extends WeixinbaseController {
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $type = I("type");
        if($type){
            $id = I("id");
            $stu_id = I("stu_id");
            $school_id = I("school_id");
            $this->check_menu($id,$stu_id,$school_id);
            return;
        }
        $userid = I("userid");//用户ID

        $openid = I("openid");//微信ID
        $schoolid  = I("schoolid");//学校ID
        $appid = I("appid");//获取公众号的appid
        $appsecret = I("appsecret");//获取公众号的appsecret
        //判断是否有空
        if (empty($userid) || empty($openid)||empty($appid) ||empty($schoolid) ||empty($appsecret)) {
            unset($userid);
            unset($openid);
            unset($appid);
            unset($appsecret);
            unset($schoolid);
        }else{
            $_SESSION["APPID"] = $appid;
            $_SESSION["APPSECRET"] = $appsecret;
            $_SESSION["user"]["weixin"] = $openid;
            //$res = M("wxtuser")->where(array("id" => $userid, "weixin" => $openid))->find();
            $res = M("xctuserwechat")->where(array("userid"=>$userid,"weixin"=>$openid))->find();
            if ($res) {
                $_SESSION["userid"] = $userid;
                $sch_info = M("school")->where(array('schoolid' => $schoolid))->find();
                if ($sch_info) {
                    $_SESSION["school_name"] = $sch_info["school_name"];
                    $_SESSION["schoolid"] = $sch_info["schoolid"];
                }
            }
        }

    }
	//老师消息渲染控制器
	//localhost/weixiaotong2016/index.php/weixin/TchInformation/index
	public function index(){
        $stu_sch_name = $_SESSION["school_name"];
        $this->assign("schoolname",$stu_sch_name);
	    $this->assign("userid",$_SESSION['userid']);
	    $this->assign("schoolid",$_SESSION['schoolid']);
		$this->display("Massage");
	}
	//详情控制器
	public function Xiang(){

        $send_user_id = I("send_user_id");
        $message_id = I("message_id");
        $schoolid = $_SESSION["schoolid"];
        //调用APPS详情接口
//        $array=R("Apps/Message/user_send_message_details",array("send_user_id"=>$send_user_id,"message_id"=>$message_id));
        $array=$this->user_send_message_details($send_user_id,$message_id,$schoolid);
        $result = json_decode($array,true);


        $stu_sch_name = $_SESSION["school_name"];
        $this->assign("schoolname",$stu_sch_name);

        $name = $result["data"][0]["send_user_name"];//发布人名字
        $content = $result["data"][0]["message_content"];//内容
        $time =  date('Y-m-d H:i:s',$result["data"][0]["message_time"]);//发布时间
        $readarray = $result["data"][0]["receiver"];
        $types = $result["data"][0]["type"];
        $h=0;
        foreach($readarray  as $k=>$v){
            if($v["read_time"]>0){
                $h++;
            }
        }
        $shuliang = count($readarray); //总数
        $yidu = $h; //已读
        $weidu=$shuliang-$h;//未读
        $subContent = $result["data"][0]['picture'];//图片
        if(count($subContent)==0){
            $sub=1;
        }else{
            $subContent=$subContent;
            $sub=0;
        }
        $this->assign("message_id",$message_id);
        $this->assign("sub",$sub);
		$this->assign("name",$name);
		$this->assign("content",$content);
		$this->assign("time",$time);
		$this->assign("subContent",$subContent);
		$this->assign("shuliang",$shuliang);
		$this->assign("yidu",$yidu);
		$this->assign("weidu",$weidu);
		$this->assign("types",$types);
		$this->display("Message_xiang");
	}

    //获取用户发送的消息详情
    public function user_send_message_details($send_user_id,$message_id,$schoolid){
//        $send_user_id =I("send_user_id");
//        $schoolid = I("schoolid");
//        $message_id = I("message_id");
        if($send_user_id){
            $where["a.send_user_id"] = $send_user_id;
        }else{
            $ret = $this->format_ret(0,'缺少参数');
            echo json_encode($ret);
            exit;
        }

        if($message_id){
            $where["a.id"] = $message_id;
        }
        if($schoolid){
            $where["teacher.schoolid"] = $schoolid;
        }

        $messages=M('user_message')
            ->alias("a")
            ->join("wxt_teacher_info teacher ON a.send_user_id=teacher.teacherid")
            ->where($where)
            ->field("a.*,teacher.name as send_user_name")
            ->order("a.message_time DESC")
            ->select();

        //获取接收人列表
        foreach ($messages as &$messageinfo) {
            $receiver=M('user_message_reception')
                ->alias("m")
                ->where(array("m.message_id"=>$messageinfo['id']))
                ->field('receiver_user_id,receiver_user_name,read_time')
                ->select();
            $messageinfo["receiver"]=$receiver;
            //赋值接收人数量
            $messageinfo["receiver_num"] = count($receiver);
            unset($messageinfo);
        }
        //获取图片列表
        foreach ($messages as &$messageinfo) {
            $picture=M('user_message')
                ->alias("m")
                ->join("wxt_user_message_pic p ON m.id=p.message_id")
                ->where(array("p.message_id"=>$messageinfo['id']))
                ->field('picture_url,width,height')
                ->select();
            $messageinfo["picture"]=$picture;
            for ($j=0; $j < count($picture); $j++) {
                $messageinfo["picture"][$j]["picturewidth"]=$picture[$j]["width"];
                $messageinfo["picture"][$j]["pictureheight"]=$picture[$j]["height"];
            }

            unset($messageinfo);
        }
        if($messages){
            $ret = $this->format_ret(1,$messages);
        }else{
            $ret = $this->format_ret(0,'未获取到数据');
        }
        return json_encode($ret);
    }

	//获取的消息
	public function Huoqu(){
        $stu_sch_name = $_SESSION["school_name"];
        $this->assign("schoolname",$stu_sch_name);
        $this->assign("userid",$_SESSION['userid']);
        $this->assign("schoolid",$_SESSION['schoolid']);
		$this->display("Massagehuoquxiaoxi");
	}


    //获取的消息详情
    public function details(){
        $receiver_user_id = I("receiver_user_id");
        $message_id = I("message_id");
        $schoolid = $_SESSION["schoolid"];
        $array=$this->user_reception_message_details($receiver_user_id,$message_id,$schoolid);
        //调用APPS详情接口
        //$array=R("Apps/Message/user_reception_message_details",array("receiver_user_id"=>$receiver_user_id,"message_id"=>$message_id));
        $result = json_decode($array,true);
//        echo "<pre>";
//        print_r($result);
//        die();
        $stu_sch_name = $_SESSION["school_name"];
        $this->assign("schoolname",$stu_sch_name);
        $name = $result["data"][0]["send_message"][0]["send_user_name"];//发布人名字
        $content = $result["data"][0]["send_message"][0]["message_content"];//内容
        $type = $result["data"][0]["send_message"][0]["type"];//类型
        $message_time = date('Y-m-d H:i:s',$result["data"][0]["send_message"][0]["message_time"]);//发布时间
        $message = $result["data"][0]["read_time"];//是否读取
        if($message==""){
            $message=0;
        }

        //已读 未读
        $readarray = $result["data"][0]["receiver"];
        $h=0;
        foreach($readarray  as $k=>$v){
            if($v["read_time"]>0){
                $h++;
            }
        }
        $zong = count($readarray); //总数
        $yidu = $h; //已读
        $Weidu=$zong-$h;//未读
        $subContent = $result["data"][0]['pic'];//图片
        if(count($subContent)==0){
            $sub=1;
        }else{
            $subContent=$subContent;
            $sub=0;
        }

        $photo = $result["data"][0]["send_message"][0]["photo"];//头像

        $this->assign("Weidu",$Weidu);
        $this->assign("Yidu",$yidu);
        $this->assign("Zong",$zong);
        $this->assign("photo",$photo);
        $this->assign("sub",$sub);
        $this->assign("name",$name);
        $this->assign("content",$content);
        $this->assign("message_time",$message_time);
        $this->assign("message_id",$message_id);
        $this->assign("message",$message);
        $this->assign("receiver_user_id",$receiver_user_id);
        $this->assign("subContent",$subContent);
        $this->assign("type",$type);
        $this->display("xiaoxixiangqing");
    }

    //获取用户已接收的信息详情
    //$receiver_user_id 接收人ID $message_id 信息ID $schoolid 学校ID
    public function user_reception_message_details($receiver_user_id,$message_id,$schoolid){
//        $receiver_user_id=Intval(I('receiver_user_id')); //用户ID
//        $message_id = I('message_id'); //消息ID
//        $schoolidss =I("schoolidss");
//        echo $schoolidss;
//        die();
        if($receiver_user_id){
            $message_where["receiver_user_id"] = $receiver_user_id;
        }else{
            $ret = $this->format_ret(0,'缺少参数');
            echo json_encode($ret);
            exit;
        }
        if($message_id){
            $message_where["message_id"] = $message_id;
        }
        if($schoolid){
            $message_where["schoolid"] = $schoolid;
            $user_where["u.schoolid"] = $schoolid;
            $user_where["teacher.schoolid"] = $schoolid;
        }
        $receive=M('user_message_reception')
            ->alias("a")
            ->field("a.id,a.message_id,a.receiver_user_id,a.receiver_user_name,a.message_type,a.read_time")
           // ->where("receiver_user_id=$receiver_user_id and message_id=$message_id")
            ->where($message_where)
            ->select();
        foreach ($receive as &$send) {
            $refid=$send['message_id'];
            $user_where["u.id"] = $refid;
            $send_message=M('user_message')
                ->alias("u")
                ->join("wxt_wxtuser w ON w.id=u.send_user_id")
                ->join("wxt_teacher_info teacher ON teacher.teacherid=u.send_user_id")
                ->field("u.id,u.schoolid,u.send_user_id,teacher.name as send_user_name,u.message_content,u.message_time,w.photo,u.type")
                //->where("u.id=$refid")
                ->where($user_where) //已发送
                //->where($user_where)
                ->order("message_time DESC")
                ->select();
            $send["send_message"]=$send_message;
            unset($send);
        }
        foreach ($receive as &$res_info) {
            $receiverid=$res_info['message_id'];
            $mes=M('user_message_reception')
                ->alias("u")
                ->join("wxt_wxtuser e ON u.receiver_user_id=e.id")
                ->field("message_id,receiver_user_id,receiver_user_name,read_time,photo,phone")
                ->where("u.message_id=$receiverid")
                ->select();
            $res_info['receiver']=$mes;
            //获取图片
            $pic=M('user_message_pic')->field("picture_url,width,height")->where("message_id=$receiverid")->select();
            $res_info['pic']=$pic;
            for ($j=0; $j < count($pic); $j++) {
                $res_info['pic'][$j]["picturewidth"]=$pic[$j]["width"];
                $res_info['pic'][$j]["pictureheight"]=$pic[$j]["height"];
            }
            unset($res_info);
        }
        if($receive){
            $ret = $this->format_ret(1,$receive);
        }else{
            $ret = $this->format_ret(0,'未获取到数据');
        }
        return json_encode($ret);
    }

    //添加老师群发信息
    public function Qunfa(){
        $stu_sch_name = $_SESSION["school_name"];
        $this->assign("schoolname",$stu_sch_name); //学校名称

        $signPackage = $this->getSignPackage();
        $this->assign('signPackage',$signPackage);
	    $userid = $_SESSION['userid']; //老师ID
	    if($_SESSION['schoolid']){
	        $schoolid = $_SESSION['schoolid'];
            $this->assign("schoolid",$_SESSION['schoolid']);
        }else{
            $tinfo= M("teacher_class")->where(array('teacherid'=>$userid))->find();
            $schoolid  = $tinfo['schoolid'];
            $this->assign("schoolid",$tinfo['schoolid']);
        }

        $this->assign('userid',$userid);
        $info = M("teacher_info")->where(array("teacherid"=>$userid,"schoolid"=>$schoolid))->find();
        $this->assign('name',$info['name']);
    	$this->display("Answer_publish");
    }
    //添加学生群发
    public function Parentfabu(){
        $stu_sch_name = $_SESSION["school_name"];
        $this->assign("schoolname",$stu_sch_name);//学校名称

        $signPackage = $this->getSignPackage();
        $this->assign('signPackage',$signPackage);
        $userid = $_SESSION['userid'];
        if($_SESSION['schoolid']){
            $schoolid = $_SESSION['schoolid'];
            $this->assign("schoolid",$_SESSION['schoolid']);//学校ID
            $this->assign("classid",$_SESSION['classid']);//班级ID
            $class= M("school_class")->where(array('id'=>$_SESSION['classid']))->field("classname")->find();
            $this->assign("classname", $class['classname']);//学校名称
        }else{
            $this->assign("classid",$_SESSION['classid']);
            $tinfo= M("teacher_class")->where(array('teacherid'=>$userid))->find();
            $schoolid = $tinfo['schoolid'];
            $this->assign("schoolid",$tinfo['schoolid']);//学校ID
            $this->assign("classid",$tinfo['classid']);;//班级ID
            $class= M("school_class")->where(array('id'=>$tinfo['classid']))->field("classname")->find();
            $this->assign("classname", $class['classname']);//学校名称
        }

        $this->assign('userid',$userid);
        //查找老师的信息
        $info = M("teacher_info")->where(array("teacherid"=>$userid,"schoolid"=>$schoolid))->find();
        $this->assign('name',$info['name']);
    	$this->display("Answer_Parent");
    }

    //查看已读未读
    public function read(){
        $stu_sch_name = $_SESSION["school_name"];
        $this->assign("schoolname",$stu_sch_name);
        $message_id = $_GET['message_id'];//信息ID
        $model = M();
        $schoolid = $_SESSION["schoolid"];
        $type = I("types");//类型
        if($type==1)
        { //发给老师
            $sql = "SELECT t.name,w.phone,w.photo,w.id FROM wxt_user_message_reception r  JOIN wxt_wxtuser w on r.receiver_user_id=w.id JOIN wxt_teacher_info t on t.teacherid=w.id  WHERE ( r.message_id='$message_id' and r.read_time>0 and t.schoolid='$schoolid')";
            $arr = "SELECT t.name,w.phone,w.photo,w.id FROM wxt_user_message_reception r  JOIN wxt_wxtuser w on r.receiver_user_id=w.id  JOIN wxt_teacher_info t on t.teacherid=w.id WHERE ( r.message_id='$message_id' and r.read_time is null  and t.schoolid='$schoolid')";
            $receive_list = $model->query($sql);
            $rlist = $model->query($arr);
            $this->assign("receive_list",$receive_list);//已读人数
            $this->assign("rlist",$rlist);//未读人数
        }

        if($type==2)
        {//发给家长
            $sql = "SELECT s.stu_name as name,w.phone,w.photo,w.id FROM wxt_user_message_reception r  JOIN wxt_wxtuser w on r.receiver_user_id=w.id JOIN wxt_student_info s on s.userid=w.id  WHERE ( r.message_id='$message_id' and r.read_time>0)";
            $arr = "SELECT s.stu_name as name,w.phone,w.photo,w.id FROM wxt_user_message_reception r  JOIN wxt_wxtuser w on r.receiver_user_id=w.id  JOIN wxt_student_info s on s.userid=w.id WHERE ( r.message_id='$message_id' and r.read_time is null)";
            $receive_list = $model->query($sql);
            $rlist = $model->query($arr);
            //dump($receive_list);
            foreach($receive_list as &$value)
            {
                $studentid = $value["id"];//学生ID
                $result = M("relation_stu_user as a")->join("wxt_wxtuser as b on a.userid=b.id")->field("b.phone")->where("a.studentid=$studentid")->find();
                $value["phone"] = $result["phone"];
            }

            foreach($rlist as &$value)
            {
                $studentid = $value["id"];//学生ID
                $result = M("relation_stu_user as a")->join("wxt_wxtuser as b on a.userid=b.id")->field("b.phone")->where("a.studentid=$studentid")->find();
                $value["phone"] = $result["phone"];
            }
            $this->assign("receive_list",$receive_list);//已读人数
            $this->assign("rlist",$rlist);//未读人数

        }

        $this->display( );
    }
	
}

