<?php
namespace Weixin\Controller;
use Common\Controller\WeixinbaseController;
class TchmobilephoneController extends WeixinbaseController {
	  function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $type = I("type");
        if($type){
            $id = I("id");
            $stu_id = I("stu_id");
            $school_id = I("school_id");
            $this->check_menu($id,$stu_id,$school_id);
            return;
        }

        $userid = I("userid");//获得用户ID
        $openid  = I("openid");//获取微信的openid
        $schoolid  = I("schoolid");//获得学校ID
        $appid = I("appid");//获取公众号的appid
        $appsecret = I("appsecret");//获取公众号的appsecret
//        判断有没有空
        if (empty($userid) || empty($openid)||empty($appid) ||empty($schoolid) ||empty($appsecret) ){
            unset($userid);
            unset($openid);
            unset($appid);
            unset($appsecret);
            unset($schoolid);
        }else {
            $_SESSION["APPID"] = $appid;
            $_SESSION["APPSECRET"] = $appsecret;
            $_SESSION["user"]["weixin"] = $openid;
            //开始写session
            $_SESSION["userid"] = $userid;
            //查询学校id 学校名字
            $sch_info = M("school")->where(array('schoolid' => $schoolid))->find();
            if ($sch_info) {
                $_SESSION["schoold_name"] = $sch_info["school_name"];
                $_SESSION["schoolid"] = $sch_info["schoolid"];
            }

        }

    }
	//教师端通讯录
	//localhost/weixiaotong2016/index.php/weixin/Tchmobilephone/index
	public function index (){
		//print_r($_SESSION);
        $stu_sch_name = $_SESSION["school_name"];

         $signPackage = $this->getSignPackage();
        $this->assign('signPackage',$signPackage);
        $this->assign("schoolname",$stu_sch_name);
	    $this->assign("schoolid",$_SESSION['schoolid']);

		$this->display("tongxun-laoshi");
	}

	public function student_add()
    {
		 $stu_sch_name = $_SESSION["school_name"];
        $this->assign("schoolname",$stu_sch_name);
       $schoolid =  $_SESSION['schoolid'];

      $grade = M("school_grade")->where("schoolid = $schoolid")->select();
         $signPackage = $this->getSignPackage();
        $this->assign('signPackage',$signPackage);
        $this->assign('grade',$grade);
        $this->display("student_add");

    }
    public function studentadd_post()
    {
        $schoolid =  $_SESSION['schoolid'];
        if (IS_POST) {
            $this -> wxtuser_model = D("Common/wxtuser");
            $this -> relation_stu_user_model = D("Common/relation_stu_user");
            $this -> relation_stu_class_model = D("Common/class_relationship");

            $photo = $_POST['photo'];
            $name = $_POST['name'];
            $sex = $_POST['sex'];
            $phone =$_POST['phone'];
            $classid = $_POST['classid'];
            $ICcard = $_POST['ICcard'];
            $relation = $_POST['relation'];
            $chusheng = $_POST['chusheng'];
            $parent = $_POST['parent'];
            if($parent=='')
            {
                $parent = $name.'家长';
            }
            if(empty($photo))
            {
                $photo = "weixiaotong.png";
            }
            if (!$sex) {
                $sex = 0;
            }
            $studentdata = array('name' => $name,  'photo'=>$photo,'schoolid' => $schoolid, 'sex' => $sex, 'password' => md5('school'), 'status' => '1', 'user_type' => '0', 'create_time' => time());

            $studentid = $this -> wxtuser_model -> add($studentdata);
            if ($studentid) {

                $classdatap['schoolid'] = $schoolid;
                $classdatap['classid'] = $classid;
                $classdatap['userid'] = $studentid;


                //添加学生班级关系
                $result =M("class_relationship")->add($classdatap);
                if($result)
                {
                    $bindingkey=rand(100000,999999);
                    $data = array(
                        'schoollid'=>$schoolid,
                        'stu_name'=>$name,
                        'sex'=>$sex,
                        'birthday'=>$chusheng,
                        'userid'=>$studentid,
                        'classid'=>$classid,
                        'stu_id'=>date('Y').$studentid,
                        'create_time'=>time(),
                        'bindingkey'=>$bindingkey,
                        'photo'=>$photo,
                    );
                    //插入学生信息表
                    $stu_info = M("student_info")->add($data);
                }
                //密码取号码后六位
                $pwd = substr($phone, -6);
                $datas=array(
                    'schoolid'=>$schoolid,
                    'name'=>$parent,
                    'phone'=>$phone,
                    'sex'=>$sex,
                    'password'=>md5($pwd),
                    'status'=>'1',
                    'user_type'=>'1',
                    'photo'=>$photo,
                    'create_time'=>time(),
                );
                $parentid=M("wxtuser")->add($datas);
                //写入亲属关系表

                $redata=array(
                    "studentid"=>$studentid,
                    "userid"=>$parentid
                );

                $redata['name']=$parent;
                $redata['phone']=$phone;
                $redata['time']=time();
                $redata['relation_rank']=1;
                $redata['type']=1;
                $redata['preferred']=1;
                $redata['charging_phone']=$phone;
                $redata['appellation']=$relation;

                $rt = $this->relation_stu_user_model->add($redata);
                if($ICcard)
                {
                    $classname = M("school_class")->where("id = $classid")->field("classname")->find();

                    $carddata  = array(
                        'schoolid'=>$schoolid,
                        'classId'=>$classid,
                        'personId'=>$studentid,
                        'className'=>$classname['classname'],
                        'cardNo'=>$ICcard,
                        'cardType'=>0,
                        'name'=>$name,
                        'imgUrl'=>$_SERVER['SERVER_NAME'].$photo,
                        'handletime'=>date("Y-m-d H:i:s",time()),
                        'handletimeint'=>time(),
                        'handletype'=>1,
                        'create_time'=>time(),
                    );

                    $card = M('student_card')->add($carddata);


                }
                if ($stu_info){
                    echo json_encode(array('success'=>1));
                }else{
                    echo json_encode(array('success'=>2));
                    //$this->error($upload->getError());

                }
            }


        }

    }
    //教师添加
    public function teacher_add()
    {
		 $stu_sch_name = $_SESSION["school_name"];
        $this->assign("schoolname",$stu_sch_name);
        $schoolid =  $_SESSION['schoolid'];

         $duty = M("school_duty")->where("schoolid = $schoolid")->select();


//        $grade = M("school_grade")->where("schoolid = $schoolid")->select();
        $signPackage = $this->getSignPackage();
        $this->assign('signPackage',$signPackage);
        $this->assign("duty",$duty);
        $this->assign("schoolid",$schoolid);
        $this->display("teacher_add");

    }
    public function teacheradd_post()
    {

       $schoolid = $_SESSION['schoolid'];
       $teacher_name = I("name");
       $sex = I('sex');
       $photo = $_POST['photo'];
       $phone = I("phone");
       $classid =rtrim(I("classid"),",");

       $ICcard = I("ICcard");
       $school_duty = I("school_duty");
       $password = substr($phone, -6);
       $class= explode(",",$classid);





       if(IS_POST)
       {
           $teacher_user = M('wxtuser')->where("schoolid = $schoolid and phone = $phone")->field("id")->find();
           if($teacher_user)
           {
               $teacherid = $teacher_user['id'];

               $data=array(
                   'photo' => $photo,
                   'schoolid'=>$schoolid,
                   'name'=>$teacher_name,
                   'phone'=>$phone,
                   'sex'=>$sex,
                   'password'=>$password,
                   'status'=>'1',
                   'user_type'=>'0',
                   'create_time'=>time()
               );
               $teacherid=M('wxtuser')->where("id = $teacherid")->save($data);

           }else{

               $data=array(
                   'photo' => $photo,
                   'schoolid'=>$schoolid,
                   'name'=>$teacher_name,
                   'phone'=>$phone,
                   'sex'=>$sex,
                   'password'=>$password,
                   'status'=>'1',
                   'user_type'=>'0',
                   'create_time'=>time()
               );



               $teacherid=M('wxtuser')->add($data);
           }

           if($teacherid)
           {
               if($ICcard)
               {
                   $carddata['cardNo']=$ICcard;
                   $carddata['imgUrl'] = 'http://'.$_SERVER['SERVER_NAME'].$photo;
                   $carddata['name'] =$teacher_name;
                   $carddata['create_time'] = time();
                   $carddata['handletime'] = date('Y-m-d H:i:s',time());
                   $carddata['handletimeint'] = time();
                   $carddata['personId']=$teacherid;
                   $carddata['schoolid']=$schoolid;
                   $carddata['create_time']=time();
                   $carddata['cardType']=1;

                   $carrs=M('student_card')->add($carddata);

               }

               foreach ($class as $val)
               {
                   $data['teacherid'] = $teacherid;
                   $data['classid'] = $val;
                   $data['schoolid'] = $schoolid;
                   $result = M('teacher_class')->add($data);
//                   $alldata[]=$data;
//                   unset($data);
               }
//               $result = M('teacher_class')->addAll($alldata);
               //添加职务信息
               $dudata=array(
                   "schoolid"=>$schoolid,
                   "duty_id"=>$school_duty,
                   "teacher_id"=>$teacherid
               );
               $rt = M("duty_teacher")->add($dudata);
               $bindingkey=rand(100000,999999);
               //添加老师个人信息wxt_teacher_info
               $teacher_info['schoolid'] = $schoolid;
               $teacher_info['teacherid'] = $teacherid;
               $teacher_info['state'] = 1;
               $teacher_info['bindingkey'] = $bindingkey;
               $rtinfo = M('teacher_info')->add($teacher_info);
               if($rtinfo && $rt)
               {
                   echo json_encode(array('success'=>1));
               }
           }else{
               echo json_encode(array('success'=>2));
           }

       }




    }

	//家长通讯
	public function jiazHuang(){
//	    dump($_SESSION);

	    $teacher_name = M("teacher_info")->where(array("teacherid"=>$_SESSION['userid'],"schoolid"=>$_SESSION["schoolid"]))->getField("name");

//	    exit();
         $stu_sch_name = $_SESSION["school_name"];
        $this->assign("schoolname",$stu_sch_name);
        $signPackage = $this->getSignPackage();
        $this->assign('signPackage',$signPackage);
        $this->assign("schoolid",$_SESSION['schoolid']);
        $this->assign("teacher_name",$teacher_name);
        $this->assign("userid",$_SESSION['userid']);
		$this->display("tongxun-jiazhang");
	}

	//获取班级
    public function get_class()
    {
        $schoolid = I("schoolid");
        $userid =  $_SESSION['userid'];
        $where['teacher.schoolid'] = $schoolid;
        $where['teacher.teacherid'] = $userid;
        $join = 'wxt_teacher_class teacher ON class.id=teacher.classid';

        $class = M('school_class')->alias("class")->join($join)->where($where)->field('class.id,class.classname')->select();

    }


    //根据年级来查出班级
    function showclass()
    {
        $schoolid =  $_SESSION['schoolid'];
        $userid =  $_SESSION['userid'];
        $gradeid = I('grade');


        $where['class.schoolid'] = $schoolid;

        $where['class.grade'] = $gradeid;

        $where['teacher.schoolid'] = $schoolid;
        $where['teacher.teacherid'] = $userid;
        $join = 'wxt_teacher_class teacher ON class.id=teacher.classid';

        $class = M('school_class')->alias("class")->join($join)->where($where)->field('class.id,class.classname')->select();


        if($class){
            $ret = $this->format_ret(1,$class);
        }else{
            $ret = $this->format_ret(0,"lost params");
        }
        echo json_encode($ret);
        exit;

    }
    function format_ret ($status, $data='') {
        if ($status){
            //成功
            return array('status'=>'success', 'data'=>$data);
        }else{
            //验证失败
            return array('status'=>'error', 'data'=>$data);
        }


    }
}
?>