<?php
namespace Weixin\Controller;
use Common\Controller\WeixinbaseController;
//	localhost/weixiaotong2016/index.php/weixin/Tell/index
//家长叮嘱
class TellController extends WeixinbaseController {

    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        $userid = I("userid");
        //获取微信的openid
        $openid  = I("openid");
        //获取学生的id
        $studentid = I("studentid");
        $schoolid = I("schoolid");//学校ID
        $appid = I("appid");//获取公众号的appid
        $appsecret = I("appsecret");//获取公众号的appsecret
        //判断是否有空
        if(empty($userid) || empty($openid) || empty($studentid)||empty($appid) ||empty($schoolid) ||empty($appsecret)){
            unset($userid);
            unset($openid);
            unset($studentid);
            unset($appid);
            unset($appsecret);
            unset($schoolid);
        }else{
            $_SESSION["APPID"] = $appid;
            $_SESSION["APPSECRET"] = $appsecret;
            $_SESSION["user"]["weixin"] = $openid;
            //$res = M("wxtuser")->where(array("id"=>$userid,"weixin"=>$openid))->find();
            $res = M("xctuserwechat")->where(array("userid"=>$userid,"weixin"=>$openid))->find();
            if ($res){
                $_SESSION["userid"] = $userid;
                $_SESSION["studentid"] = $studentid;
                //顺带查出来学校id 学校名字 学生班级
                $sch_info = M("school")->where(array('schoolid' => $schoolid))->find();
                if ($sch_info){
                    $_SESSION["school_name"] = $sch_info["school_name"];
                    $_SESSION["schoolid"] = $sch_info["schoolid"];
                }
            }
//            }
        }

    }

    /*
     * 叮嘱
     */
	public function index(){
        $stu_sch_name = $_SESSION["school_name"];
        $this->assign("schoolname",$stu_sch_name);//学校名称
		    $this->assign("userid",$_SESSION['userid']);//家长ID
		    $this->assign("studentid",$_SESSION['studentid']);//学生ID
		    $this->assign("classid",$_SESSION['classid']);//班级ID
		    $this->assign("schoolid",$_SESSION['schoolid']);//学校ID
			$this->display();
	}
	//发布家长叮嘱
	public function Tianjian(){
        $stu_sch_name = $_SESSION["school_name"];
        $this->assign("schoolname",$stu_sch_name);
        $signPackage = $this->getSignPackage();
        $stu_info = M("relation_stu_user")->where(array('userid'=>$_SESSION['userid'],"stdnetid"=>$_SESSION['studentid']))->find();
        $name = $stu_info['name']; //获取家长姓名
        $this->assign('name',$name);
        $this->assign('signPackage',$signPackage);
        $this->assign('classid',$_SESSION['classid']);
        $this->assign('schoolid',$_SESSION['schoolid']);
        $this->assign('studentid',$_SESSION['studentid']);
        $this->assign('userid',$_SESSION['userid']);

		$this->display("MessageBoard");
	}

}




