<?php
namespace Weixin\Controller;
use Common\Controller\WeixinbaseController;
session_start();
header("Content-type:text/html;charset=utf-8");
class TusercenterController extends WeixinbaseController{
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $type = I("type");
        if($type){
            $id = I("id");
            $stu_id = I("stu_id");
            $school_id = I("school_id");
            $this->check_menu($id,$stu_id,$school_id);
            return;
        }
//        $this->check_session();//查看session 是否过期
        $userid = I("userid");//获得用户ID
        $openid  = I("openid");//获取微信的openid
        $schoolid  = I("schoolid");//获得学校ID
        $appid = I("appid");//获取公众号的appid
        $appsecret = I("appsecret");//获取公众号的appsecret
//        判断有没有空
        if (empty($userid) || empty($openid)||empty($appid) ||empty($schoolid) ||empty($appsecret) ){
            unset($userid);
            unset($openid);
            unset($appid);
            unset($appsecret);
            unset($schoolid);
        }else {
            $_SESSION["APPID"] = $appid;
            $_SESSION["APPSECRET"] = $appsecret;
            $_SESSION["user"]["weixin"] = $openid;
            //开始写session
            $_SESSION["userid"] = $userid;
            //查询学校id 学校名字
            $sch_info = M("school")->where(array('schoolid' => $schoolid))->find();
            if ($sch_info) {
                $_SESSION["schoold_name"] = $sch_info["school_name"];
                $_SESSION["schoolid"] = $sch_info["schoolid"];
            }

        }
    }
    function index()
    {
        $userid = $_SESSION['userid'];
        $schoolid = $_SESSION['schoolid'];
        //查询老师的信息
        $user_info = M("wxtuser")->where(array("id"=>$userid))->find();
        //头像
        $photo = $user_info["photo"];
        $headimg = str_replace(",","",$photo);
        if ($headimg ==null){
//            $headimg = __ROOT__."/uploads/microblog/weixiaotong.png";//默认头像
            $headimg = SR."weixiaotong.png";//默认头像
        }elseif(strpos($headimg,"ttp://")){
            $headimg =$headimg;//微信绑定的头像
        }
        else{
            //$headimg = __ROOT__."/uploads/microblog/".$headimg;//自己上传的头像
            $headimg = SR.$headimg;//自己上传的头像
        }
        $this->assign("headimg",$headimg);
        //获取代理商电话
        if($_SESSION['schoolid']){
            $schoolid = $_SESSION['schoolid'];
            $agent = M("agent_school_del")->where("schoolid = $schoolid")->find();
        }
//        $schoolid = $user_info['schoolid'];
//        $agent = M("agent_school_del")->where("schoolid = $schoolid")->find();
        if(!empty($agent)){
            $id = $agent['agentid'];
            $agentinfo = M("agent")->where("id = $id")->find();
            $servicephone= $agentinfo["servicephone"];
            $this->assign("servicephone", $servicephone);
        }

//        $result = R('Apps/Role/weixin_role',array(2,5,1));
//        $result1 = R('Apps/Role/weixin_role',array(2,5,2));
//        $result2 = R('Apps/Role/weixin_role',array(2,5,3));
//
//
//        foreach ($result as $key => $v) {
//            $top_menu[$key] = $v['name'];
//        }
//
//        foreach ($result1 as $key => $v) {
//            $middle_menu[$key] = $v['name'];
//        }
//
//        foreach ($result2 as $key => $v) {
//            $bottom_menu[$key] = $v['name'];
//        }
//        $this->assign("top_menu",$top_menu);
//        $this->assign("middle_menu",$middle_menu);
//        $this->assign("bottom_menu",$bottom_menu);
        //查询老师的信息
        $teacher_info = M("teacher_info")->where(array("teacherid"=>$userid,"schoolid"=>$schoolid))->field("name")->find();
        $this->assign("name",$teacher_info["name"]);//名字
        $this->assign("school_name",$_SESSION["school_name"]);//学校名称
        $this->display();
    }
    function Userinfo(){

        $signPackage = $this->getSignPackage();
        $this->assign('signPackage',$signPackage);
        $userid = $_SESSION['userid'];
        $schoolid = $_SESSION['schoolid'];
        $this->assign("userid",$userid);
        //查询用户的所还有信息
        $userinfo = M("wxtuser")->where(array("id"=>$userid))->find();
        $teacherinfo = M("teacher_info")->where(array("teacherid"=>$userid,"schoolid"=>$schoolid))->find();
        unset($userinfo["password"]);
        $headimg = $userinfo["photo"];//头像
        if ($headimg ==null){
//            $headimg = __ROOT__."/uploads/microblog/weixiaotong.png";//默认头像
            $headimg = SR."weixiaotong.png";//默认头像
        }elseif(strpos($headimg,"ttp://")){
            $headimg =$headimg;//微信绑定的头像
        }
        else{
            //$headimg = __ROOT__."/uploads/microblog/".$headimg;//自己上传的头像
            $headimg = SR.$headimg;//自己上传的头像
        }
        $this->assign("headimg",$headimg);
        $this->assign("name",$teacherinfo["name"]);//姓名
        $this->assign("phone",$userinfo["phone"]);//电话
        $this->assign("sex",$userinfo["sex"]);//性别
       // $this->assign("headimg",$userinfo["photo"]);//头像
        $this->assign("schoolname",$_SESSION["school_name"]);//学校名字
        $this->display();
    }


    //修改用户信息
    public function upload(){
        $teacherdata["name"] = I('name');
        $data["sex"] = I('sex');
        $data["phone"] = I('phone');
        if(I('photo')){
            $data['photo'] = I('photo');
        }
        //入库更新
        array_filter($data);
        $res = M("wxtuser")->where(array("id"=>$_SESSION["userid"]))->save($data);
        $reslut = M("teacher_info")->where(array("teacherid"=>$_SESSION["userid"],"schoolid"=>$_SESSION["schoolid"]))->save($teacherdata);

        if ($res){
            echo json_encode(array('success'=>1));
        }else{
            echo json_encode(array('success'=>2));
            //$this->error($upload->getError());

        }

    }

    function MessageBoard(){
        $stu_sch_name = $_SESSION["school_name"];
        $this->assign("schoolname",$stu_sch_name);
//        $jssdk = new JSSDK("wx7325155f62456567","c379e9768f9faa8865a1db767fc81155");
//        $signPackage = $jssdk->GetSignPackage();
        $signPackage = $this->getSignPackage();
        $this->assign('userid',$_SESSION['userid']);
        $this->assign('signPackage',$signPackage);
        $this->display();
    }
    function resetPwd(){
        $stu_sch_name = $_SESSION["school_name"];
        $this->assign("schoolname",$stu_sch_name);
        $userid = $_SESSION["userid"];
        $this->assign("userid",$userid);
        $this->display();
    }

}


