<?php
/**
 * Created by PhpStorm.
 * User: 10987
 * Date: 2017/3/10
 * Time: 16:03
 */
namespace Weixin\Controller;
use Common\Controller\WeixinbaseController;
header("Content-type:text/html;charset=utf-8");
class UsercenterController extends WeixinbaseController
{
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $type = I("type");
        if($type){
            $id = I("id");
            $stu_id = I("stu_id");
            $school_id = I("school_id");
            $this->check_menu($id,$stu_id,$school_id);
            return;
        }

        $userid = I("userid");
        //获取微信的openid
        $openid  = I("openid");
        //获取学生的id
        $studentid = I("studentid");
        $schoolid = I("schoolid");//学校ID
        $appid = I("appid");//获取公众号的appid
        $appsecret = I("appsecret");//获取公众号的appsecret
        //判断是否有空
        if(empty($userid) || empty($openid) || empty($studentid)||empty($appid) ||empty($schoolid) ||empty($appsecret)){
            unset($userid);
            unset($openid);
            unset($studentid);
            unset($appid);
            unset($appsecret);
            unset($schoolid);
        }else{
            $_SESSION["APPID"] = $appid;
            $_SESSION["APPSECRET"] = $appsecret;
            $_SESSION["user"]["weixin"] = $openid;
            //$res = M("wxtuser")->where(array("id"=>$userid,"weixin"=>$openid))->find();
            $res = M("xctuserwechat")->where(array("userid"=>$userid,"weixin"=>$openid))->find();
            if ($res){
                $_SESSION["userid"] = $userid;
                $_SESSION["studentid"] = $studentid;
                //顺带查出来学校id 学校名字 学生班级
                $sch_info = M("school")->where(array('schoolid' => $schoolid))->find();
                if ($sch_info){
                    $_SESSION["school_name"] = $sch_info["school_name"];
                    $_SESSION["schoolid"] = $sch_info["schoolid"];
                }
            }
//            }
        }

    }
    public function Userinfo(){

        $signPackage = $this->getSignPackage();
        $this->assign('signPackage',$signPackage);
        $studentid = $_SESSION['studentid'];
        $this->assign("studentid",$studentid);
        //查询用户信息
        $userid = $_SESSION['userid'];
        $userinfo = M("wxtuser")->where(array("id"=>$userid))->find();

        $headimg = $userinfo["photo"];//头像
        if ($headimg ==null){
            $headimg = __ROOT__."/uploads/microblog/weixiaotong.png";//默认头像
        }elseif(strpos($headimg,"ttp://")){
            $headimg =$headimg;//微信绑定的头像
        }
        else{
            $headimg = SR.$headimg;//自己上传的头像
        }

        $info = M("relation_stu_user")->where(array("userid"=>$userid,"studentid"=>$studentid))->find();
        $name = $info["name"];

        $this->assign("headimg",$headimg);
        $this->assign("name",$name);//姓名
        $this->assign("phone",$userinfo["phone"]);//电话
        $this->assign("sex",$userinfo["sex"]);//性别
       // $this->assign("headimg",$userinfo["photo"]);//头像
        $this->assign("schoolname",$_SESSION["school_name"]);//学校名字
        $this->display();
    }

    /**家长个人中心
     *
     *
     */
    function index(){
       //dump($_SESSION);
        $stu_sch_name = $_SESSION["school_name"];//学校名称
        $this->assign("schoolname",$stu_sch_name);

        $userid = $_SESSION['userid'];//家长ID
        $studentid = $_SESSION["studentid"];//学生ID

        $userinfo = M("wxtuser")->where("id = '$userid'")->find();
        $headimg = $userinfo["photo"];//头像
        if ($headimg ==null){
            $headimg = SR."weixiaotong.png";//默认头像
        }elseif(strpos($headimg,"ttp://")){
            $headimg =$headimg;//微信绑定的头像
        }
        else{
            $headimg = SR.$headimg;//自己上传的头像
        }

        $this->assign("headimg",$headimg);

        $info = M("relation_stu_user")->where(array("userid"=>$userid,"studentid"=>$studentid))->find();
        $name = $info["name"];
        $_SESSION["name"] = $name;
        $sex = $userinfo["sex"];
        if ($sex == 1){
            $sex = "男";
        }else{
            $sex = "女";
        }

        //获取代理商电话
        if($_SESSION['schoolid']){
            $schoolid = $_SESSION['schoolid'];
            $agent = M("agent_school_del")->where("schoolid = $schoolid")->find();
        }
//        $schoolid = $_SESSION['schoolid'];
//        $agent = M("agent_school_del")->where("schoolid = $schoolid")->find();
        if(!empty($agent)){
            $id = $agent['agentid'];
            $agentinfo = M("agent")->where("id = $id")->find();
            $servicephone= $agentinfo["servicephone"];
            $this->assign("servicephone", $servicephone);
        }

        $phone = $userinfo["phone"];


//        $result = R('Apps/Role/weixin_role',array(1,5,1));
//
//        $result1 = R('Apps/Role/weixin_role',array(1,5,2));
//
//        $result2 = R('Apps/Role/weixin_role',array(1,5,3));
//
//
//
//        foreach ($result as $key => $v) {
//            $top_menu[$key] = $v['name'];
//        }
//
//
//
//        foreach ($result1 as $key => $v) {
//            $middle_menu[$key] = $v['name'];
//        }
//
//        foreach ($result2 as $key => $v) {
//            $bottom_menu[$key] = $v['name'];
//        }
//
//        $this->assign("top_menu",$top_menu);
//        $this->assign("middle_menu",$middle_menu);
//        $this->assign("bottom_menu",$bottom_menu);

        $this->assign("name",$name);
        $this->assign("sex",$sex);
        $this->assign("phone",$phone);
        $this->display();
    }

    //邀请家人页面
    function Invitefamily(){
        //dump($_SESSION);
        $stu_sch_name = $_SESSION["school_name"];//学校名称
        $this->assign("schoolname",$stu_sch_name);

        $signPackage = $this->getSignPackage();//获取appid等信息

        $studentid = $_SESSION["studentid"]; //学生ID
        $userid = $_SESSION["userid"]; //学生ID
        $student = M("student_info")->where(array('userid'=>$studentid))->find(); //查找学生信息
        //dump($student);
        $stu_name = $student["stu_name"]; //学生姓名
        $bindingkey = $student["bindingkey"]; //绑定码

        //查询学生的关系列表
        $result = M("relation_stu_user as relation")
            ->join("wxt_wxtuser as user on relation.userid = user.id")
            ->field("user.phone,user.photo,relation.name,relation.appellation")
            ->where(array("studentid"=>$studentid))
            ->select();
        //查找公众号信息等
        $appid = $_SESSION["APPID"];
        $manage = M("wxmanage")->where(array("wx_appid"=>$appid))->find();
        if(count($manage)){
            $id = $manage["id"];//公众号ID
            $manage_name = $manage["wx_name"];//公众号ID
            $this->assign("id",$id);
            $this->assign("manage_name",$manage_name);
        }
        $schoolid = $_SESSION["schoolid"];//学校ID
        $this->assign("schoolid",$schoolid);
        $this->assign("bindingkey",$bindingkey);
        $this->assign("result",$result);
        $this->assign("signPackage",$signPackage);
        $this->assign("stu_name",$stu_name);
        $this->assign("studentid",$studentid);
        //输出到页面
        $this->display();
    }
    function yaoqing(){
        $stu_sch_name = $_SESSION["school_name"];
        $this->assign("schoolname",$stu_sch_name);
        $this->display();
    }
    function ChangeBaby(){
		 $stu_sch_name = $_SESSION["school_name"];
        $this->assign("schoolname",$stu_sch_name);
        $userid = $_SESSION["userid"];
        $stu_real_res = M("relation_stu_user as relation")
            ->join("wxt_wxtuser as user on relation.studentid = user.id")
            ->join("wxt_student_info as student on student.userid = user.id")
//            ->join("wxt_class_relationship as class on relation.studentid = class.userid")
//            ->join("wxt_school_class as sclass on sclass.id = class.classid")
//            ->join("wxt_school as school on school.schoolid = sclass.schoolid")
            //->field("studentid,appellation,school_name,classname,user.name,user.photo")
            ->field("studentid,appellation,student.stu_name as name,user.photo")
            ->where("relation.userid = '$userid'")
            ->select();
        $this->assign("userid",$_SESSION["userid"]);
        $this->assign("stus",$stu_real_res);
//        print_r($stu_real_res);
        $this->display();
    }
    function Board(){
        $stu_sch_name = $_SESSION["school_name"];
        $this->assign("schoolname",$stu_sch_name);
        $Board = M("guestbook")->select();

        echo json_encode($Board);
    }
    function MessageBoard(){
        $stu_sch_name = $_SESSION["school_name"];
        $this->assign("schoolname",$stu_sch_name);
//        $jssdk = new JSSDK("wx7325155f62456567","c379e9768f9faa8865a1db767fc81155");
//        $signPackage = $jssdk->GetSignPackage();
        $signPackage = $this->getSignPackage();
        $this->assign('signPackage',$signPackage);
        $this->assign('classid',$_SESSION['classid']);
        $this->assign('schoolid',$_SESSION['schoolid']);
        $this->assign('studentid',$_SESSION['studentid']);
        $this->assign('userid',$_SESSION['userid']);
        $this->display();
    }
    function getSelfMessage()
    {
        $stu_sch_name = $_SESSION["school_name"];
        $this->assign("schoolname",$stu_sch_name);
        $userid = $_SESSION["userid"];
        $this->assign("userid",$userid);
        $this->display();
    }
    function SystermMessage(){
        $stu_sch_name = $_SESSION["school_name"];
        $this->assign("schoolname",$stu_sch_name);
        $this->display();
    }
    function resetPwd(){
        $stu_sch_name = $_SESSION["school_name"];
        $this->assign("schoolname",$stu_sch_name);
        $userid = $_SESSION["userid"];
        $this->assign("userid",$userid);
        $this->display();
    }
    //修改用户信息
//    public function upload(){
//        if ($_FILES){
//            $array['date'] = date('YmdHis', mktime());
//            $array['name'] = rand(1000, 9999);
//            $name = implode($array);//定义一个命名规则
//
//            $upload = new \Think\Upload();// 实例化上传类
//            $upload->maxSize   =     3145728888 ;// 设置附件上传大小 3MB
//            $upload->exts      =     array('jpg', 'gif', 'png', 'jpeg');// 设置附件上传类型
//            $upload->rootPath  =     './uploads/'; // 设置附件上传根目录
//            $upload->savePath  =     '/microbloghub/'; // 设置附件上传（子）目录
//            $upload->saveName  =     $name;//图片名字
//            $upload->autoSub = false;
//            // 上传文件
//            $info   =   $upload->upload();
//            if(!$info) {// 上传错误提示错误信息
//               // $this->error($upload->getError());
//            }else{// 上传成功
//                foreach($info as $file){
//                    $data["photo"] = $file['savename'];
//                    $imgSrc = "./uploads".$file['savepath'].$file['savename'];//图片路径
//                    $filetype = $file['ext'];//图片格式
//                    //调用压缩借口
//                    R('Apps/index/resizeImage',array("imgSrc"=>$imgSrc,"maxwidth"=>200,"maxheight"=>200,"filetype"=>$filetype));
//                }
//            }
//            $data["name"] = $_POST["name"];
//            $data["sex"] = $_POST["sex"];
//            $data["phone"] = $_POST["tel"];
//            //入库更新
//            array_filter($data);
//            $res = M("wxtuser")->where(array("id"=>$_SESSION["userid"]))->save($data);
//        }else{
//            $data["name"] = $_POST["name"];
//            $data["sex"] = $_POST["sex"];
//            $data["phone"] = $_POST["tel"];
//            //入库更新
//            array_filter($data);
//            $res = M("wxtuser")->where(array("id"=>$_SESSION["userid"]))->save($data);
//        }
//        if ($res){
//           $this->success("上传成功");
//        }else{
//            $this->error($upload->getError());
//
//        }
//
//    }

    //修改用户信息
    public function upload(){
            $userid = $_SESSION['userid'];//家长ID
            $studentid = $_SESSION["studentid"];//学生ID
            $userdata["name"] = I('name');
            $data["sex"] = I('sex');
            $data["phone"] = I('phone');
            if(I('photo')){
                $data['photo'] = I('photo');
            }
            //入库更新
            array_filter($data);
            $res = M("wxtuser")->where(array("id"=>$userid))->save($data);
            $res = M("relation_stu_user")->where(array("userid"=>$userid,"studentid"=>$studentid))->save($userdata);
            if ($res){
                echo json_encode(array('success'=>1));
            }else{
                echo json_encode(array('success'=>2));
                //$this->error($upload->getError());

            }

    }

    //宝宝个人信息
    function BabyUserinfo(){

        $signPackage = $this->getSignPackage();
        $this->assign('signPackage',$signPackage);
        $studentid = $_SESSION['studentid'];//学生ID
        $this->assign("studentid",$studentid);
        //查询宝宝信息
        $userinfo = M("wxtuser")->where(array("id"=> $studentid))->find();
        $headimg = $userinfo["photo"];//头像
        if ($headimg ==null){
            $headimg = SR."weixiaotong.png";//默认头像
        }elseif(strpos($headimg,"ttp://")){
            $headimg =$headimg;//微信绑定的头像
        }
        else{
            $headimg = SR.$headimg;//自己上传的头像
        }
        //获取学生名字
        $student = M("student_info")->where(array('userid'=>$studentid))->field("stu_name,sex")->find();
        $stu_name = $student['stu_name'];
        $sex = $student['sex'];
        $this->assign("headimg",$headimg);
        $this->assign("name",$stu_name);//姓名
        $this->assign("sex",$sex);//性别
        $this->assign("schoolname",$_SESSION["school_name"]);//学校名字
        $this->display();
    }
    //修改用户信息
    public function BabyUpload(){
        $data["name"] = I('name');
        $data["sex"] = I('sex');
        if(I('photo')){
            $data['photo'] = I('photo');
        }
        $studentid = $_SESSION['studentid'];//学生ID
        //入库更新
        array_filter($data);
        $res = M("wxtuser")->where(array("id"=>$studentid))->save($data);
        $query["stu_name"]= I('name');
        $query["sex"] = I('sex');
        $card["name"]=I('name');
        //$ress = M("student_card")->where(array("cardType"=>0,"schoolid"=>$_SESSION["schoolid"],"personId"=>$studentid,"handletype"=>1))->save($card);
        $arr = M("student_info")->where(array("userid"=>$studentid))->save($query);
        if ($res){
            echo json_encode(array('success'=>1));
        }else{
            echo json_encode(array('success'=>2));
            //$this->error($upload->getError());

        }



    }

}


